XTD: xtd::thread::raii_thread_manual Class Reference
xtd::thread::raii_thread_manual Class Reference
#include <raii_thread_manual.hpp>
Public Member Functions
raii_thread_manual (std::function< void()> client_routine)
virtual ~raii_thread_manual (void) noexcept override
void start (void)
void stop (void)
bool get_is_initialized (void) const
Protected Member Functions
void initialize_routine (void)
void deinitialize_routine (void)
void check_is_initialized (void) const
void check_is_not_initialized (void) const
Static Protected Member Functions
static void routine (raii_thread_base *raii_thread_base_ptr)
Protected Attributes
bool terminate_flag
std::function< void()> client_routine
std::thread thread
std::recursive_mutex mutex
Detailed Description
Definition at line 12 of file raii_thread_manual.hpp.
Constructor & Destructor Documentation
xtd::thread::raii_thread_manual::raii_thread_manual (std::function< void()> client_routine) explicit
Definition at line 9 of file raii_thread_manual.cpp.
                    :
                        raii_thread_base(client_routine)
        {
        }
xtd::thread::raii_thread_manual::~raii_thread_manual (void) override virtual
Definition at line 16 of file raii_thread_manual.cpp.
References xtd::thread::raii_thread_base::get_is_initialized(), and stop().
        {
            try
            {
                if ( this->get_is_initialized() == true )
                {
                    this->stop();
                }
            }
            catch ( ... )
            {
            }
        }
Member Function Documentation
void xtd::thread::raii_thread_base::check_is_initialized (void) const protected inherited
Definition at line 57 of file raii_thread_base.cpp.
References xtd::thread::raii_thread_base::get_is_initialized().
Referenced by xtd::thread::raii_thread_base::deinitialize_routine().
        {
            if ( this->get_is_initialized() == false )
            {
                throw std::runtime_error("Thread is not initialized");
            }
        }
void xtd::thread::raii_thread_base::check_is_not_initialized (void) const protected inherited
Definition at line 65 of file raii_thread_base.cpp.
References xtd::thread::raii_thread_base::get_is_initialized().
Referenced by xtd::thread::raii_thread_base::initialize_routine().
        {
            if ( this->get_is_initialized() == true )
            {
                throw std::runtime_error("Thread is already initialized");
            }
        }
void xtd::thread::raii_thread_base::deinitialize_routine (void) protected inherited
Definition at line 35 of file raii_thread_base.cpp.
References xtd::thread::raii_thread_base::check_is_initialized(), xtd::thread::raii_thread_base::mutex, xtd::thread::raii_thread_base::terminate_flag, and xtd::thread::raii_thread_base::thread.
Referenced by stop(), and xtd::thread::raii_thread::~raii_thread().
        {
            std::unique_lock<std::recursive_mutex> lock(this->mutex);
            this->check_is_initialized();
            this->terminate_flag = true;
            lock.unlock();
            //  Join the "thread" only if this function is not executed from it
            //  Omitting the condition will lead to a freeze if this function is executed from the "thread"
            if ( std::this_thread::get_id() != this->thread.get_id() )
            {
                this->thread.join();
            }
            //  Thread must be joined or detached before termination
            else
            {
                this->thread.detach();
            }
        }
bool xtd::thread::raii_thread_base::get_is_initialized (void) const inherited
Definition at line 22 of file raii_thread_base.cpp.
References xtd::thread::raii_thread_base::thread.
Referenced by xtd::thread::raii_thread_base::check_is_initialized(), xtd::thread::raii_thread_base::check_is_not_initialized(), and ~raii_thread_manual().
        {
            return ( this->thread.joinable() == true );
        }
void xtd::thread::raii_thread_base::initialize_routine (void) protected inherited
Definition at line 27 of file raii_thread_base.cpp.
References xtd::thread::raii_thread_base::check_is_not_initialized(), xtd::thread::raii_thread_base::mutex, xtd::thread::raii_thread_base::routine(), xtd::thread::raii_thread_base::terminate_flag, and xtd::thread::raii_thread_base::thread.
Referenced by xtd::thread::raii_thread::raii_thread(), and start().
        {
            std::lock_guard<std::recursive_mutex> lock(this->mutex);
            this->check_is_not_initialized();
            this->terminate_flag = false;
            this->thread = std::thread(raii_thread_base::routine,this);
        }
void xtd::thread::raii_thread_base::routine (raii_thread_base * raii_thread_base_ptr) static protected inherited
Definition at line 73 of file raii_thread_base.cpp.
References xtd::thread::raii_thread_base::client_routine, xtd::thread::raii_thread_base::mutex, and xtd::thread::raii_thread_base::terminate_flag.
Referenced by xtd::thread::raii_thread_base::initialize_routine().
        {
            while ( true )
            {
                try
                {
                    //    Check if the thread is supposed to be terminated
                    std::unique_lock<std::recursive_mutex> terminate_unique_lock(raii_thread_base_ptr->mutex,std::defer_lock);
                    terminate_unique_lock.try_lock();
                    if ( raii_thread_base_ptr->terminate_flag )
                    {
                        return;
                    }
                    //    Run client code
                    (raii_thread_base_ptr->client_routine)();
                    //    Yield to other threads
                    std::this_thread::yield();
                }
                catch ( ... )
                {
                    //    Ignore errors
                }
            }
        }
void xtd::thread::raii_thread_manual::start (void)
Definition at line 31 of file raii_thread_manual.cpp.
References xtd::thread::raii_thread_base::initialize_routine().
        {
            this->initialize_routine();
        }
void xtd::thread::raii_thread_manual::stop (void)
Definition at line 36 of file raii_thread_manual.cpp.
References xtd::thread::raii_thread_base::deinitialize_routine().
Referenced by ~raii_thread_manual().
        {
            this->deinitialize_routine();
        }
Member Data Documentation
std::function<void()> xtd::thread::raii_thread_base::client_routine protected inherited
Definition at line 27 of file raii_thread_base.hpp.
Referenced by xtd::thread::raii_thread_base::routine().
std::recursive_mutex xtd::thread::raii_thread_base::mutex protected inherited
Definition at line 29 of file raii_thread_base.hpp.
Referenced by xtd::thread::raii_thread_base::deinitialize_routine(), xtd::thread::raii_thread_base::initialize_routine(), and xtd::thread::raii_thread_base::routine().
bool xtd::thread::raii_thread_base::terminate_flag protected inherited
Definition at line 26 of file raii_thread_base.hpp.
Referenced by xtd::thread::raii_thread_base::deinitialize_routine(), xtd::thread::raii_thread_base::initialize_routine(), and xtd::thread::raii_thread_base::routine().
std::thread xtd::thread::raii_thread_base::thread protected inherited
Definition at line 28 of file raii_thread_base.hpp.
Referenced by xtd::thread::raii_thread_base::deinitialize_routine(), xtd::thread::raii_thread_base::get_is_initialized(), and xtd::thread::raii_thread_base::initialize_routine().
The documentation for this class was generated from the following files:
sources/thread/raii_thread_manual/sources/raii_thread_manual.hpp
sources/thread/raii_thread_manual/sources/raii_thread_manual.cpp