XTD: xtd::log::console_logger Class Reference
xtd::log::console_logger Class Reference
#include <console_logger.hpp>
Public Member Functions
console_logger (bool add_new_line=true, bool add_time_stamp=true) noexcept
void log (const std::string &data) const noexcept
Public Attributes
bool add_new_line
bool add_time_stamp
Protected Member Functions
virtual void log_data (const std::string &data) const noexcept override
void log_new_line (void) const noexcept
void log_time_stamp (void) const noexcept
Static Protected Member Functions
static std::string make_time_stamp (void) noexcept
Detailed Description
Definition at line 13 of file console_logger.hpp.
Constructor & Destructor Documentation
xtd::log::console_logger::console_logger (bool add_new_line = true, bool add_time_stamp = true) explicit
Definition at line 9 of file console_logger.cpp.
            :
                abstract_logger(add_new_line,add_time_stamp)
        {
}
Member Function Documentation
void xtd::log::abstract_logger::log (const std::string & data) const inherited
Definition at line 17 of file abstract_logger.cpp.
Referenced by TEST().
        {
            this->log_time_stamp();
            this->log_data(data);
            this->log_new_line();
        }
void xtd::log::console_logger::log_data (const std::string & data) const override protected virtual
Implements xtd::log::abstract_logger.
Definition at line 16 of file console_logger.cpp.
References xtd::io::scout.
        {
            xtd::io::scout << data;
        }
void xtd::log::abstract_logger::log_new_line (void) const protected inherited
Definition at line 26 of file abstract_logger.cpp.
References xtd::log::abstract_logger::add_new_line, and xtd::log::abstract_logger::log_data().
        {
            if ( this->add_new_line )
            {
                this->log_data("\n");
            }
        }
void xtd::log::abstract_logger::log_time_stamp (void) const protected inherited
Definition at line 38 of file abstract_logger.cpp.
References xtd::log::abstract_logger::add_time_stamp, xtd::log::abstract_logger::log_data(), and xtd::log::abstract_logger::make_time_stamp().
        {
            if ( this->add_time_stamp )
            {
                this->log_data(abstract_logger::make_time_stamp() + " - ");
            }
        }
std::string xtd::log::abstract_logger::make_time_stamp (void) static protected inherited
Definition at line 50 of file abstract_logger.cpp.
References xtd::chrono::time_point_to_formatted_string().
Referenced by xtd::log::abstract_logger::log_time_stamp().
        {
            std::chrono::time_point<std::chrono::steady_clock> time_current = std::chrono::steady_clock::now();
            std::string time_current_string = xtd::chrono::time_point_to_formatted_string(time_current);
            return time_current_string;
        }
Member Data Documentation
bool xtd::log::abstract_logger::add_new_line inherited
Definition at line 22 of file abstract_logger.hpp.
Referenced by xtd::log::abstract_logger::log_new_line().
bool xtd::log::abstract_logger::add_time_stamp inherited
Definition at line 24 of file abstract_logger.hpp.
Referenced by xtd::log::abstract_logger::log_time_stamp().
The documentation for this class was generated from the following files:
sources/log/console_logger/sources/console_logger.hpp
sources/log/console_logger/sources/console_logger.cpp