XTD: xtd::event::event< data_type > Class Template Reference
xtd::event::event< data_type > Class Template Reference
#include <event.hpp>
Public Member Functions
virtual ~event (void) noexcept
unsigned int get_listeners_count (void) const
unsigned int get_free_listeners_count (void) const
unsigned int get_functor_listeners_count (void) const
bool has_listener (free_listener free_listener_instance) const
template<typename object_type >
bool has_listener (object_type *object_ptr, void(object_type::*method_ptr)(data_type...)) const
void add_listener (free_listener free_listener_instance)
template<typename object_type >
void add_listener (object_type *object_ptr, void(object_type::*method_ptr)(data_type...))
void remove_listener (free_listener free_listener_instance)
template<typename object_type >
void remove_listener (object_type *object_ptr, void(object_type::*method_ptr)(data_type...))
void dispatch (data_type...data) const
Protected Member Functions
void check_has_listener (free_listener free_listener_instance) const
template<typename object_type >
void check_has_listener (object_type *object_ptr, void(object_type::*method_ptr)(data_type...)) const
void check_has_no_listener (free_listener free_listener_instance) const
template<typename object_type >
void check_has_no_listener (object_type *object_ptr, void(object_type::*method_ptr)(data_type...)) const
free_listeners_collection_itr get_listener_itr (free_listener free_listener_instance) const
template<typename object_type >
functor_listeners_collection_itr get_listener_itr (object_type *object_ptr, void(object_type::*method_ptr)(data_type...)) const
void dispatch_free_listeners (data_type...data) const
void dispatch_functor_listeners (data_type...data) const
Protected Attributes
free_listeners_collection free_listeners
functor_listeners_collection functor_listeners
std::recursive_mutex master_mutex
Detailed Description
template<typename... data_type>
class xtd::event::event< data_type >
Definition at line 16 of file event.hpp.
Constructor & Destructor Documentation
template<typename... data_type> virtual xtd::event::event< data_type >::~event (void) inline virtual
Definition at line 40 of file event.hpp.
References xtd::event::event< data_type >::functor_listeners.
                {
                    try
                    {
                        for ( abstract_functor_listener* abstract_functor_listener_ptr : this->functor_listeners )
{
                            try
{
                                delete abstract_functor_listener_ptr;
                            }
                            catch ( ... )
{
                            }
                        }
                    }
                    catch ( ... )
                    {
                    }
                }
Member Function Documentation
template<typename... data_type> void xtd::event::event< data_type >::add_listener (free_listener free_listener_instance) inline
Definition at line 98 of file event.hpp.
References xtd::event::event< data_type >::check_has_no_listener(), xtd::event::event< data_type >::free_listeners, and xtd::event::event< data_type >::master_mutex.
                {
                    std::lock_guard<std::recursive_mutex> master_lock_guard(this->master_mutex);
                    this->check_has_no_listener(free_listener_instance);
                    this->free_listeners.push_back(free_listener_instance);
                }
template<typename... data_type> template<typename object_type > void xtd::event::event< data_type >::add_listener (object_type * object_ptr, void(object_type::*)(data_type...) method_ptr) inline
Definition at line 106 of file event.hpp.
References xtd::event::event< data_type >::check_has_no_listener(), xtd::event::event< data_type >::functor_listeners, and xtd::event::event< data_type >::master_mutex.
                {
                    std::lock_guard<std::recursive_mutex> master_lock_guard(this->master_mutex);
                    this->check_has_no_listener(object_ptr,method_ptr);
                    this->functor_listeners.push_back(new functor_listener<object_type>(object_ptr,method_ptr));
                }
template<typename... data_type> void xtd::event::event< data_type >::check_has_listener (free_listener free_listener_instance) const inline protected
Definition at line 137 of file event.hpp.
References xtd::event::event< data_type >::has_listener().
Referenced by xtd::event::event< data_type >::remove_listener().
                {
                    if ( this->has_listener(free_listener_instance) == false )
                    {
                        throw -1;
                    }
                }
template<typename... data_type> template<typename object_type > void xtd::event::event< data_type >::check_has_listener (object_type * object_ptr, void(object_type::*)(data_type...) method_ptr) const inline protected
Definition at line 146 of file event.hpp.
References xtd::event::event< data_type >::has_listener().
                {
                    if ( this->has_listener(object_ptr,method_ptr) == false )
                    {
                        throw -1;
                    }
                }
template<typename... data_type> void xtd::event::event< data_type >::check_has_no_listener (free_listener free_listener_instance) const inline protected
Definition at line 154 of file event.hpp.
References xtd::event::event< data_type >::has_listener().
Referenced by xtd::event::event< data_type >::add_listener().
                {
                    if ( this->has_listener(free_listener_instance) == true )
                    {
                        throw -1;
                    }
                }
template<typename... data_type> template<typename object_type > void xtd::event::event< data_type >::check_has_no_listener (object_type * object_ptr, void(object_type::*)(data_type...) method_ptr) const inline protected
Definition at line 163 of file event.hpp.
References xtd::event::event< data_type >::has_listener().
                {
                    if ( this->has_listener(object_ptr,method_ptr) == true )
                    {
                        throw -1;
                    }
                }
template<typename... data_type> void xtd::event::event< data_type >::dispatch (data_type... data) const inline
Definition at line 128 of file event.hpp.
References xtd::event::event< data_type >::dispatch_free_listeners(), xtd::event::event< data_type >::dispatch_functor_listeners(), and xtd::event::event< data_type >::master_mutex.
                {
                    std::lock_guard<std::recursive_mutex> master_lock_guard(this->master_mutex);
                    this->dispatch_free_listeners(data...);
                    this->dispatch_functor_listeners(data...);
                }
template<typename... data_type> void xtd::event::event< data_type >::dispatch_free_listeners (data_type... data) const inline protected
Definition at line 208 of file event.hpp.
References xtd::event::event< data_type >::free_listeners.
Referenced by xtd::event::event< data_type >::dispatch().
                {
                    free_listeners_collection freeListeners_copy = this->free_listeners;
                    for ( free_listener free_listener_instance : freeListeners_copy )
                    {
                        free_listener_instance(data...);
                    }
                }
template<typename... data_type> void xtd::event::event< data_type >::dispatch_functor_listeners (data_type... data) const inline protected
Definition at line 217 of file event.hpp.
References xtd::event::event< data_type >::functor_listeners.
Referenced by xtd::event::event< data_type >::dispatch().
                {
                    functor_listeners_collection functorListeners_copy = this->functor_listeners;
                    for ( abstract_functor_listener* abstractFunctorListenerPtr : functorListeners_copy )
                    {
                        (*abstractFunctorListenerPtr)(data...);
                    }
                }
template<typename... data_type> unsigned int xtd::event::event< data_type >::get_free_listeners_count (void) const inline
Definition at line 73 of file event.hpp.
References xtd::event::event< data_type >::free_listeners, and xtd::event::event< data_type >::master_mutex.
Referenced by xtd::event::event< data_type >::get_listeners_count().
                {
                    std::lock_guard<std::recursive_mutex> master_lock_guard(this->master_mutex);
                    return this->free_listeners.size();
                }
template<typename... data_type> unsigned int xtd::event::event< data_type >::get_functor_listeners_count (void) const inline
Definition at line 79 of file event.hpp.
References xtd::event::event< data_type >::functor_listeners, and xtd::event::event< data_type >::master_mutex.
Referenced by xtd::event::event< data_type >::get_listeners_count().
                {
                    std::lock_guard<std::recursive_mutex> master_lock_guard(this->master_mutex);
                    return this->functor_listeners.size();
                }
template<typename... data_type> free_listeners_collection_itr xtd::event::event< data_type >::get_listener_itr (free_listener free_listener_instance) const inline protected
Definition at line 171 of file event.hpp.
References xtd::event::event< data_type >::free_listeners.
Referenced by xtd::event::event< data_type >::has_listener(), and xtd::event::event< data_type >::remove_listener().
                {
                    free_listeners_collection_itr free_listeners_itr = this->free_listeners.begin();
                    while ( free_listeners_itr != this->free_listeners.end() )
                    {
                        if ( *free_listeners_itr == free_listener_instance )
{
                            break;
                        }
                        free_listeners_itr++;
                    }
                    return free_listeners_itr;
                }
template<typename... data_type> template<typename object_type > functor_listeners_collection_itr xtd::event::event< data_type >::get_listener_itr (object_type * object_ptr, void(object_type::*)(data_type...) method_ptr) const inline protected
Definition at line 186 of file event.hpp.
References xtd::event::event< data_type >::functor_listeners.
                {
                    functor_listeners_collection_itr functor_listeners_itr = this->functor_listeners.begin();
                    while ( functor_listeners_itr != this->functor_listeners.end() )
                    {
                        functor_listener<object_type>* functor_listener_ptr = dynamic_cast<functor_listener<object_type>*>(*functor_listeners_itr);
                        if
                        (
                            functor_listener_ptr != nullptr
                                &&
                            functor_listener_ptr->object_ptr == object_ptr
                                &&
                            functor_listener_ptr->method_ptr == method_ptr
                        )
{
                            break;
                        }
                        functor_listeners_itr++;
                    }
                    return functor_listeners_itr;
                }
template<typename... data_type> unsigned int xtd::event::event< data_type >::get_listeners_count (void) const inline
Definition at line 62 of file event.hpp.
References xtd::event::event< data_type >::get_free_listeners_count(), xtd::event::event< data_type >::get_functor_listeners_count(), and xtd::event::event< data_type >::master_mutex.
                {
                    std::lock_guard<std::recursive_mutex> master_lock_guard(this->master_mutex);
                    return
                    (
                        this->get_free_listeners_count()
                            +
                        this->get_functor_listeners_count()
                    );
                }
template<typename... data_type> bool xtd::event::event< data_type >::has_listener (free_listener free_listener_instance) const inline
Definition at line 85 of file event.hpp.
References xtd::event::event< data_type >::free_listeners, xtd::event::event< data_type >::get_listener_itr(), and xtd::event::event< data_type >::master_mutex.
Referenced by xtd::event::event< data_type >::check_has_listener(), and xtd::event::event< data_type >::check_has_no_listener().
                {
                    std::lock_guard<std::recursive_mutex> master_lock_guard(this->master_mutex);
                    return this->get_listener_itr(free_listener_instance) != this->free_listeners.end();
                }
template<typename... data_type> template<typename object_type > bool xtd::event::event< data_type >::has_listener (object_type * object_ptr, void(object_type::*)(data_type...) method_ptr) const inline
Definition at line 92 of file event.hpp.
References xtd::event::event< data_type >::functor_listeners, xtd::event::event< data_type >::get_listener_itr(), and xtd::event::event< data_type >::master_mutex.
                {
                    std::lock_guard<std::recursive_mutex> master_lock_guard(this->master_mutex);
                    return this->get_listener_itr(object_ptr,method_ptr) != this->functor_listeners.end();
                }
template<typename... data_type> void xtd::event::event< data_type >::remove_listener (free_listener free_listener_instance) inline
Definition at line 113 of file event.hpp.
References xtd::event::event< data_type >::check_has_listener(), xtd::event::event< data_type >::free_listeners, xtd::event::event< data_type >::get_listener_itr(), and xtd::event::event< data_type >::master_mutex.
                {
                    std::lock_guard<std::recursive_mutex> master_lock_guard(this->master_mutex);
                    this->check_has_listener(free_listener_instance);
                    this->free_listeners.erase(this->get_listener_itr(free_listener_instance));
                }
template<typename... data_type> template<typename object_type > void xtd::event::event< data_type >::remove_listener (object_type * object_ptr, void(object_type::*)(data_type...) method_ptr) inline
Definition at line 121 of file event.hpp.
References xtd::event::event< data_type >::check_has_listener(), xtd::event::event< data_type >::functor_listeners, xtd::event::event< data_type >::get_listener_itr(), and xtd::event::event< data_type >::master_mutex.
                {
                    std::lock_guard<std::recursive_mutex> master_lock_guard(this->master_mutex);
                    this->check_has_listener(object_ptr,method_ptr);
                    this->functor_listeners.erase(this->get_listener_itr(object_ptr,method_ptr));
                }
Member Data Documentation
template<typename... data_type> free_listeners_collection xtd::event::event< data_type >::free_listeners mutable protected
Definition at line 226 of file event.hpp.
Referenced by xtd::event::event< data_type >::add_listener(), xtd::event::event< data_type >::dispatch_free_listeners(), xtd::event::event< data_type >::get_free_listeners_count(), xtd::event::event< data_type >::get_listener_itr(), xtd::event::event< data_type >::has_listener(), and xtd::event::event< data_type >::remove_listener().
template<typename... data_type> functor_listeners_collection xtd::event::event< data_type >::functor_listeners mutable protected
Definition at line 228 of file event.hpp.
Referenced by xtd::event::event< data_type >::add_listener(), xtd::event::event< data_type >::dispatch_functor_listeners(), xtd::event::event< data_type >::get_functor_listeners_count(), xtd::event::event< data_type >::get_listener_itr(), xtd::event::event< data_type >::has_listener(), xtd::event::event< data_type >::remove_listener(), and xtd::event::event< data_type >::~event().
template<typename... data_type> std::recursive_mutex xtd::event::event< data_type >::master_mutex mutable protected
Definition at line 230 of file event.hpp.
Referenced by xtd::event::event< data_type >::add_listener(), xtd::event::event< data_type >::dispatch(), xtd::event::event< data_type >::get_free_listeners_count(), xtd::event::event< data_type >::get_functor_listeners_count(), xtd::event::event< data_type >::get_listeners_count(), xtd::event::event< data_type >::has_listener(), and xtd::event::event< data_type >::remove_listener().
The documentation for this class was generated from the following file:
sources/event/event/sources/event.hpp