XTD: xstd::chrono::timer< clock > Class Template Reference
xstd::chrono::timer< clock > Class Template Reference
#include <timer.hpp>
Public Member Functions
timer (void)
virtual ~timer (void) noexcept
bool get_is_active (void) const
void get_ticks_done (void) const
void start (void)
void stop (void)
Public Attributes
duration tick_interval
unsigned int tick_limit
event_start_type event_start
event_tick_type event_tick
event_complete_type event_complete
event_stop_type event_stop
Protected Member Functions
bool requires_tick (void)
virtual void tick (void) override
void update_next_tick_time_point (void)
void check_is_ready_to_start (void) const
void check_is_ready_to_stop (void) const
Protected Attributes
bool is_active
unsigned int ticks_done
time_point next_tick_time_point
Detailed Description
template<typename clock = std::chrono::high_resolution_clock>
class xstd::chrono::timer< clock >
Definition at line 34 of file timer.hpp.
Constructor & Destructor Documentation
template<typename clock = std::chrono::high_resolution_clock> xstd::chrono::timer< clock >::timer (void) inline explicit
Definition at line 54 of file timer.hpp.
                                            :
                                                is_active(false),
                                                ticks_done(0)
                {
                }
template<typename clock = std::chrono::high_resolution_clock> virtual xstd::chrono::timer< clock >::~timer (void) inline virtual
Definition at line 62 of file timer.hpp.
References xstd::chrono::timer< clock >::stop().
                {
                    try
                    {
                        this->stop();
                    }
                    catch ( ... )
                    {
                        //  timer may be already stopped
                    }
                }
Member Function Documentation
template<typename clock = std::chrono::high_resolution_clock> void xstd::chrono::timer< clock >::check_is_ready_to_start (void) const inline protected
Definition at line 147 of file timer.hpp.
References xstd::chrono::timer< clock >::is_active, and xstd::chrono::timer< clock >::tick_interval.
Referenced by xstd::chrono::timer< clock >::start().
                {
                    if
                    (
                        this->tick_interval.count() == 0
                            ||
                        this->is_active == true
                    )
                    {
                        throw std::runtime_error("Timer is not ready to start");
                    }
                }
template<typename clock = std::chrono::high_resolution_clock> void xstd::chrono::timer< clock >::check_is_ready_to_stop (void) const inline protected
Definition at line 160 of file timer.hpp.
References xstd::chrono::timer< clock >::is_active.
Referenced by xstd::chrono::timer< clock >::stop().
                {
                    if ( this->is_active == false )
                    {
                        throw std::runtime_error("Timer is already stopped");
                    }
                }
template<typename clock = std::chrono::high_resolution_clock> bool xstd::chrono::timer< clock >::get_is_active (void) const inline
Definition at line 74 of file timer.hpp.
References xstd::chrono::timer< clock >::is_active.
Referenced by TEST().
                {
                    return this->is_active;
                }
template<typename clock = std::chrono::high_resolution_clock> void xstd::chrono::timer< clock >::get_ticks_done (void) const inline
Definition at line 79 of file timer.hpp.
References xstd::chrono::timer< clock >::ticks_done.
                {
                    return this->ticks_done();
                }
template<typename clock = std::chrono::high_resolution_clock> bool xstd::chrono::timer< clock >::requires_tick (void) inline protected
Definition at line 116 of file timer.hpp.
References xstd::chrono::timer< clock >::next_tick_time_point.
Referenced by xstd::chrono::timer< clock >::tick().
                {
                    return clock::now() >= this->next_tick_time_point;
                }
template<typename clock = std::chrono::high_resolution_clock> void xstd::chrono::timer< clock >::start (void) inline
Definition at line 84 of file timer.hpp.
References xstd::chrono::timer_manager::add_timer(), xstd::chrono::timer< clock >::check_is_ready_to_start(), xstd::chrono::timer< clock >::event_start, xstd::chrono::timer_manager::get_instance(), xstd::chrono::timer< clock >::is_active, and xstd::chrono::timer< clock >::update_next_tick_time_point().
Referenced by TEST().
                {
                    this->check_is_ready_to_start();
                    timer_manager::get_instance().add_timer(this);
                    this->update_next_tick_time_point();
                    this->is_active = true;
                    this->event_start.dispatch();
                }
template<typename clock = std::chrono::high_resolution_clock> void xstd::chrono::timer< clock >::stop (void) inline
Definition at line 93 of file timer.hpp.
References xstd::chrono::timer< clock >::check_is_ready_to_stop(), xstd::chrono::timer< clock >::event_stop, xstd::chrono::timer_manager::get_instance(), xstd::chrono::timer< clock >::is_active, xstd::chrono::timer_manager::remove_timer(), and xstd::chrono::timer< clock >::ticks_done.
Referenced by xstd::chrono::timer< clock >::tick(), and xstd::chrono::timer< clock >::~timer().
                {
                    this->check_is_ready_to_stop();
                    timer_manager::get_instance().remove_timer(this);
                    this->is_active = false;
                    this->ticks_done = 0;
                    this->event_stop.dispatch();
                }
template<typename clock = std::chrono::high_resolution_clock> virtual void xstd::chrono::timer< clock >::tick (void) inline override protected virtual
Implements xstd::chrono::timer_base.
Definition at line 121 of file timer.hpp.
References xstd::chrono::timer< clock >::event_complete, xstd::chrono::timer< clock >::event_tick, xstd::chrono::timer< clock >::requires_tick(), xstd::chrono::timer< clock >::stop(), xstd::chrono::timer< clock >::tick_limit, xstd::chrono::timer< clock >::ticks_done, and xstd::chrono::timer< clock >::update_next_tick_time_point().
                {
                    if ( this->requires_tick() == true )
                    {
                        this->ticks_done++;
                        this->update_next_tick_time_point();
                        this->event_tick.dispatch(this->ticks_done);
                        if ( this->ticks_done == this->tick_limit )
{
                            this->event_complete.dispatch();
                            this->stop();
                            return;
                        }
                    }
                }
template<typename clock = std::chrono::high_resolution_clock> void xstd::chrono::timer< clock >::update_next_tick_time_point (void) inline protected
Definition at line 142 of file timer.hpp.
References xstd::chrono::timer< clock >::next_tick_time_point, and xstd::chrono::timer< clock >::tick_interval.
Referenced by xstd::chrono::timer< clock >::start(), and xstd::chrono::timer< clock >::tick().
                {
                    this->next_tick_time_point = clock::now() + this->tick_interval;
                }
Member Data Documentation
template<typename clock = std::chrono::high_resolution_clock> event_complete_type xstd::chrono::timer< clock >::event_complete
Definition at line 110 of file timer.hpp.
Referenced by xstd::chrono::timer< clock >::tick().
template<typename clock = std::chrono::high_resolution_clock> event_start_type xstd::chrono::timer< clock >::event_start
Definition at line 106 of file timer.hpp.
Referenced by xstd::chrono::timer< clock >::start().
template<typename clock = std::chrono::high_resolution_clock> event_stop_type xstd::chrono::timer< clock >::event_stop
Definition at line 112 of file timer.hpp.
Referenced by xstd::chrono::timer< clock >::stop().
template<typename clock = std::chrono::high_resolution_clock> event_tick_type xstd::chrono::timer< clock >::event_tick
Definition at line 108 of file timer.hpp.
Referenced by TEST(), and xstd::chrono::timer< clock >::tick().
template<typename clock = std::chrono::high_resolution_clock> bool xstd::chrono::timer< clock >::is_active protected
Definition at line 170 of file timer.hpp.
Referenced by xstd::chrono::timer< clock >::check_is_ready_to_start(), xstd::chrono::timer< clock >::check_is_ready_to_stop(), xstd::chrono::timer< clock >::get_is_active(), xstd::chrono::timer< clock >::start(), and xstd::chrono::timer< clock >::stop().
template<typename clock = std::chrono::high_resolution_clock> time_point xstd::chrono::timer< clock >::next_tick_time_point protected
Definition at line 174 of file timer.hpp.
Referenced by xstd::chrono::timer< clock >::requires_tick(), and xstd::chrono::timer< clock >::update_next_tick_time_point().
template<typename clock = std::chrono::high_resolution_clock> duration xstd::chrono::timer< clock >::tick_interval
Definition at line 102 of file timer.hpp.
Referenced by xstd::chrono::timer< clock >::check_is_ready_to_start(), TEST(), and xstd::chrono::timer< clock >::update_next_tick_time_point().
template<typename clock = std::chrono::high_resolution_clock> unsigned int xstd::chrono::timer< clock >::tick_limit
Definition at line 104 of file timer.hpp.
Referenced by TEST(), and xstd::chrono::timer< clock >::tick().
template<typename clock = std::chrono::high_resolution_clock> unsigned int xstd::chrono::timer< clock >::ticks_done protected
Definition at line 172 of file timer.hpp.
Referenced by xstd::chrono::timer< clock >::get_ticks_done(), xstd::chrono::timer< clock >::stop(), and xstd::chrono::timer< clock >::tick().
The documentation for this class was generated from the following file:
src/chrono/timer/timer/src/timer.hpp