XTD: xtd::thread::raii_thread_base Class Reference
xtd::thread::raii_thread_base Class Reference
#include <raii_thread_base.hpp>
Public Member Functions
raii_thread_base (std::function< void()> client_routine)
virtual ~raii_thread_base (void) noexcept
bool get_is_initialized (void) const
Protected Member Functions
void initialize_routine (void)
void deinitialize_routine (void)
void check_is_initialized (void) const
void check_is_not_initialized (void) const
Static Protected Member Functions
static void routine (raii_thread_base *raii_thread_base_ptr)
Protected Attributes
bool terminate_flag
std::function< void()> client_routine
std::thread thread
std::recursive_mutex mutex
Private Member Functions
raii_thread_base (const raii_thread_base &rhs)
raii_thread_base & operator= (const raii_thread_base &rhs)
Detailed Description
Definition at line 14 of file raii_thread_base.hpp.
Constructor & Destructor Documentation
xtd::thread::raii_thread_base::raii_thread_base (std::function< void()> client_routine) explicit
Definition at line 9 of file raii_thread_base.cpp.
            :
                terminate_flag(false),
                client_routine(client_routine)
        {
        }
xtd::thread::raii_thread_base::~raii_thread_base (void) virtual
Definition at line 17 of file raii_thread_base.cpp.
        {
        }
xtd::thread::raii_thread_base::raii_thread_base (const raii_thread_base & rhs) explicit private
Member Function Documentation
void xtd::thread::raii_thread_base::check_is_initialized (void) const protected
Definition at line 57 of file raii_thread_base.cpp.
References get_is_initialized().
Referenced by deinitialize_routine().
        {
            if ( this->get_is_initialized() == false )
            {
                throw std::runtime_error("Thread is not initialized");
            }
        }
void xtd::thread::raii_thread_base::check_is_not_initialized (void) const protected
Definition at line 65 of file raii_thread_base.cpp.
References get_is_initialized().
Referenced by initialize_routine().
        {
            if ( this->get_is_initialized() == true )
            {
                throw std::runtime_error("Thread is already initialized");
            }
        }
void xtd::thread::raii_thread_base::deinitialize_routine (void) protected
Definition at line 35 of file raii_thread_base.cpp.
References check_is_initialized(), mutex, terminate_flag, and thread.
Referenced by xtd::thread::raii_thread_manual::stop(), and xtd::thread::raii_thread::~raii_thread().
        {
            std::unique_lock<std::recursive_mutex> lock(this->mutex);
            this->check_is_initialized();
            this->terminate_flag = true;
            lock.unlock();
            //  Join the "thread" only if this function is not executed from it
            //  Omitting the condition will lead to a freeze if this function is executed from the "thread"
            if ( std::this_thread::get_id() != this->thread.get_id() )
            {
                this->thread.join();
            }
            //  Thread must be joined or detached before termination
            else
            {
                this->thread.detach();
            }
        }
bool xtd::thread::raii_thread_base::get_is_initialized (void) const
Definition at line 22 of file raii_thread_base.cpp.
References thread.
Referenced by check_is_initialized(), check_is_not_initialized(), and xtd::thread::raii_thread_manual::~raii_thread_manual().
        {
            return ( this->thread.joinable() == true );
        }
void xtd::thread::raii_thread_base::initialize_routine (void) protected
Definition at line 27 of file raii_thread_base.cpp.
References check_is_not_initialized(), mutex, routine(), terminate_flag, and thread.
Referenced by xtd::thread::raii_thread::raii_thread(), and xtd::thread::raii_thread_manual::start().
        {
            std::lock_guard<std::recursive_mutex> lock(this->mutex);
            this->check_is_not_initialized();
            this->terminate_flag = false;
            this->thread = std::thread(raii_thread_base::routine,this);
        }
raii_thread_base& xtd::thread::raii_thread_base::operator= (const raii_thread_base & rhs) private
void xtd::thread::raii_thread_base::routine (raii_thread_base * raii_thread_base_ptr) static protected
Definition at line 73 of file raii_thread_base.cpp.
References client_routine, mutex, and terminate_flag.
Referenced by initialize_routine().
        {
            while ( true )
            {
                try
                {
                    //    Check if the thread is supposed to be terminated
                    std::unique_lock<std::recursive_mutex> terminate_unique_lock(raii_thread_base_ptr->mutex,std::defer_lock);
                    terminate_unique_lock.try_lock();
                    if ( raii_thread_base_ptr->terminate_flag )
                    {
                        return;
                    }
                    //    Run client code
                    (raii_thread_base_ptr->client_routine)();
                    //    Yield to other threads
                    std::this_thread::yield();
                }
                catch ( ... )
                {
                    //    Ignore errors
                }
            }
        }
Member Data Documentation
std::function<void()> xtd::thread::raii_thread_base::client_routine protected
Definition at line 27 of file raii_thread_base.hpp.
Referenced by routine().
std::recursive_mutex xtd::thread::raii_thread_base::mutex protected
Definition at line 29 of file raii_thread_base.hpp.
Referenced by deinitialize_routine(), initialize_routine(), and routine().
bool xtd::thread::raii_thread_base::terminate_flag protected
Definition at line 26 of file raii_thread_base.hpp.
Referenced by deinitialize_routine(), initialize_routine(), and routine().
std::thread xtd::thread::raii_thread_base::thread protected
Definition at line 28 of file raii_thread_base.hpp.
Referenced by deinitialize_routine(), get_is_initialized(), and initialize_routine().
The documentation for this class was generated from the following files:
sources/thread/raii_thread_base/sources/raii_thread_base.hpp
sources/thread/raii_thread_base/sources/raii_thread_base.cpp