XSTD: xstd::raii_thread_manual Class Reference
xstd::raii_thread_manual Class Reference
#include <raii_thread_manual.hpp>
Public Member Functions
raii_thread_manual (std::function< void()> client_routine)
virtual ~raii_thread_manual (void) noexcept override
void start (void)
void stop (void)
Public Member Functions inherited from xstd::raii_thread_base
raii_thread_base (std::function< void()> client_routine)
virtual ~raii_thread_base (void) noexcept
bool get_is_initialized (void) const
Additional Inherited Members
Protected Member Functions inherited from xstd::raii_thread_base
void initialize_routine (void)
void deinitialize_routine (void)
void check_is_initialized (void) const
void check_is_not_initialized (void) const
Static Protected Member Functions inherited from xstd::raii_thread_base
static void routine (raii_thread_base *raii_thread_base_ptr)
Protected Attributes inherited from xstd::raii_thread_base
bool terminate_flag
std::function< void()> client_routine
std::thread thread
std::recursive_mutex mutex
Detailed Description
Definition at line 26 of file raii_thread_manual.hpp.
Constructor & Destructor Documentation
xstd::raii_thread_manual::raii_thread_manual (std::function< void()> client_routine) inline explicit
Definition at line 22 of file raii_thread_manual.ipp.
                :
                    raii_thread_base(client_routine)
    {
    }
xstd::raii_thread_manual::~raii_thread_manual (void) inline override virtual
Definition at line 29 of file raii_thread_manual.ipp.
References xstd::raii_thread_base::get_is_initialized(), and stop().
    {
        try
        {
            if ( this->get_is_initialized() == true )
            {
                this->stop();
            }
        }
        catch ( ... )
        {
        }
    }
Member Function Documentation
void xstd::raii_thread_manual::start (void) inline
Definition at line 44 of file raii_thread_manual.ipp.
References xstd::raii_thread_base::initialize_routine().
    {
        this->initialize_routine();
    }
void xstd::raii_thread_manual::stop (void) inline
Definition at line 49 of file raii_thread_manual.ipp.
References xstd::raii_thread_base::deinitialize_routine().
Referenced by ~raii_thread_manual().
    {
        this->deinitialize_routine();
    }
The documentation for this class was generated from the following files:
src/thread/raii_thread_manual/src/raii_thread_manual.hpp
src/thread/raii_thread_manual/src/raii_thread_manual.ipp