XTD: xtd::chrono::timer< clock > Class Template Reference
xtd::chrono::timer< clock > Class Template Reference
#include <timer.hpp>
Public Member Functions
timer (void)
virtual ~timer (void) noexcept
bool get_is_active (void) const
void get_ticks_done (void) const
void start (void)
void stop (void)
Public Attributes
duration tick_interval
unsigned int tick_limit
event_start_type event_start
event_tick_type event_tick
event_complete_type event_complete
event_stop_type event_stop
Protected Member Functions
bool requires_tick (void)
virtual void tick (void) override
void update_next_tick_time_point (void)
void check_is_ready_to_start (void) const
void check_is_ready_to_stop (void) const
Protected Attributes
bool is_active
unsigned int ticks_done
time_point next_tick_time_point
Detailed Description
template<typename clock = std::chrono::high_resolution_clock>
class xtd::chrono::timer< clock >
Definition at line 16 of file timer.hpp.
Constructor & Destructor Documentation
template<typename clock = std::chrono::high_resolution_clock> xtd::chrono::timer< clock >::timer (void) inline explicit
Definition at line 35 of file timer.hpp.
                            :
                                is_active(false),
                                ticks_done(0)
                {
                }
template<typename clock = std::chrono::high_resolution_clock> virtual xtd::chrono::timer< clock >::~timer (void) inline virtual
Definition at line 43 of file timer.hpp.
References xtd::chrono::timer< clock >::stop().
                {
                    try
                    {
                        this->stop();
                    }
                    catch ( ... )
                    {
                        //  timer may be already stopped
                    }
                }
Member Function Documentation
template<typename clock = std::chrono::high_resolution_clock> void xtd::chrono::timer< clock >::check_is_ready_to_start (void) const inline protected
Definition at line 128 of file timer.hpp.
References xtd::chrono::timer< clock >::is_active, and xtd::chrono::timer< clock >::tick_interval.
Referenced by xtd::chrono::timer< clock >::start().
                {
                    if
                    (
                        this->tick_interval.count() == 0
                            ||
                        this->is_active == true
                    )
                    {
                        throw std::runtime_error("Timer is not ready to start");
                    }
                }
template<typename clock = std::chrono::high_resolution_clock> void xtd::chrono::timer< clock >::check_is_ready_to_stop (void) const inline protected
Definition at line 141 of file timer.hpp.
References xtd::chrono::timer< clock >::is_active.
Referenced by xtd::chrono::timer< clock >::stop().
                {
                    if ( this->is_active == false )
                    {
                        throw std::runtime_error("Timer is already stopped");
                    }
                }
template<typename clock = std::chrono::high_resolution_clock> bool xtd::chrono::timer< clock >::get_is_active (void) const
template<typename clock = std::chrono::high_resolution_clock> void xtd::chrono::timer< clock >::get_ticks_done (void) const inline
Definition at line 60 of file timer.hpp.
References xtd::chrono::timer< clock >::ticks_done.
                {
                    return this->ticks_done();
                }
template<typename clock = std::chrono::high_resolution_clock> bool xtd::chrono::timer< clock >::requires_tick (void) inline protected
Definition at line 97 of file timer.hpp.
References xtd::chrono::timer< clock >::next_tick_time_point.
Referenced by xtd::chrono::timer< clock >::tick().
                {
                    return clock::now() >= this->next_tick_time_point;
                }
template<typename clock = std::chrono::high_resolution_clock> void xtd::chrono::timer< clock >::start (void) inline
Definition at line 65 of file timer.hpp.
References xtd::chrono::timer_manager::add_timer(), xtd::chrono::timer< clock >::check_is_ready_to_start(), xtd::chrono::timer< clock >::event_start, xtd::chrono::timer_manager::get_instance(), xtd::chrono::timer< clock >::is_active, and xtd::chrono::timer< clock >::update_next_tick_time_point().
                {
                    this->check_is_ready_to_start();
                    timer_manager::get_instance().add_timer(this);
                    this->update_next_tick_time_point();
                    this->is_active = true;
                    this->event_start.dispatch();
                }
template<typename clock = std::chrono::high_resolution_clock> void xtd::chrono::timer< clock >::stop (void) inline
Definition at line 74 of file timer.hpp.
References xtd::chrono::timer< clock >::check_is_ready_to_stop(), xtd::chrono::timer< clock >::event_stop, xtd::chrono::timer_manager::get_instance(), xtd::chrono::timer< clock >::is_active, xtd::chrono::timer_manager::remove_timer(), and xtd::chrono::timer< clock >::ticks_done.
Referenced by xtd::chrono::timer< clock >::tick(), and xtd::chrono::timer< clock >::~timer().
                {
                    this->check_is_ready_to_stop();
                    timer_manager::get_instance().remove_timer(this);
                    this->is_active = false;
                    this->ticks_done = 0;
                    this->event_stop.dispatch();
                }
template<typename clock = std::chrono::high_resolution_clock> virtual void xtd::chrono::timer< clock >::tick (void) inline override protected virtual
Implements xtd::chrono::timer_base.
Definition at line 102 of file timer.hpp.
References xtd::chrono::timer< clock >::event_complete, xtd::chrono::timer< clock >::event_tick, xtd::chrono::timer< clock >::requires_tick(), xtd::chrono::timer< clock >::stop(), xtd::chrono::timer< clock >::tick_limit, xtd::chrono::timer< clock >::ticks_done, and xtd::chrono::timer< clock >::update_next_tick_time_point().
                {
                    if ( this->requires_tick() == true )
                    {
                        this->ticks_done++;
                        this->update_next_tick_time_point();
                        this->event_tick.dispatch(this->ticks_done);
                        if ( this->ticks_done == this->tick_limit )
{
                            this->event_complete.dispatch();
                            this->stop();
                            return;
                        }
                    }
                }
template<typename clock = std::chrono::high_resolution_clock> void xtd::chrono::timer< clock >::update_next_tick_time_point (void) inline protected
Definition at line 123 of file timer.hpp.
References xtd::chrono::timer< clock >::next_tick_time_point, and xtd::chrono::timer< clock >::tick_interval.
Referenced by xtd::chrono::timer< clock >::start(), and xtd::chrono::timer< clock >::tick().
                {
                    this->next_tick_time_point = clock::now() + this->tick_interval;
                }
Member Data Documentation
template<typename clock = std::chrono::high_resolution_clock> event_complete_type xtd::chrono::timer< clock >::event_complete
Definition at line 91 of file timer.hpp.
Referenced by xtd::chrono::timer< clock >::tick().
template<typename clock = std::chrono::high_resolution_clock> event_start_type xtd::chrono::timer< clock >::event_start
Definition at line 87 of file timer.hpp.
Referenced by xtd::chrono::timer< clock >::start().
template<typename clock = std::chrono::high_resolution_clock> event_stop_type xtd::chrono::timer< clock >::event_stop
Definition at line 93 of file timer.hpp.
Referenced by xtd::chrono::timer< clock >::stop().
template<typename clock = std::chrono::high_resolution_clock> event_tick_type xtd::chrono::timer< clock >::event_tick
Definition at line 89 of file timer.hpp.
Referenced by xtd::chrono::timer< clock >::tick().
template<typename clock = std::chrono::high_resolution_clock> bool xtd::chrono::timer< clock >::is_active protected
Definition at line 151 of file timer.hpp.
Referenced by xtd::chrono::timer< clock >::check_is_ready_to_start(), xtd::chrono::timer< clock >::check_is_ready_to_stop(), xtd::chrono::timer< clock >::start(), and xtd::chrono::timer< clock >::stop().
template<typename clock = std::chrono::high_resolution_clock> time_point xtd::chrono::timer< clock >::next_tick_time_point protected
Definition at line 155 of file timer.hpp.
Referenced by xtd::chrono::timer< clock >::requires_tick(), and xtd::chrono::timer< clock >::update_next_tick_time_point().
template<typename clock = std::chrono::high_resolution_clock> duration xtd::chrono::timer< clock >::tick_interval
Definition at line 83 of file timer.hpp.
Referenced by xtd::chrono::timer< clock >::check_is_ready_to_start(), and xtd::chrono::timer< clock >::update_next_tick_time_point().
template<typename clock = std::chrono::high_resolution_clock> unsigned int xtd::chrono::timer< clock >::tick_limit
Definition at line 85 of file timer.hpp.
Referenced by xtd::chrono::timer< clock >::tick().
template<typename clock = std::chrono::high_resolution_clock> unsigned int xtd::chrono::timer< clock >::ticks_done protected
Definition at line 153 of file timer.hpp.
Referenced by xtd::chrono::timer< clock >::get_ticks_done(), xtd::chrono::timer< clock >::stop(), and xtd::chrono::timer< clock >::tick().
The documentation for this class was generated from the following file:
sources/chrono/timer/timer/sources/timer.hpp