XTD: xtd::fn::functor< object_type, arguments_type > Class Template Reference
xtd::fn::functor< object_type, arguments_type > Class Template Reference
#include <functor.hpp>
Public Member Functions
functor (object_type *object_ptr, void(object_type::*method_ptr)(arguments_type...))
virtual ~functor (void) noexcept override
virtual void operator() (arguments_type...arguments) const override final
virtual void invoke (arguments_type...arguments) const override final
Public Attributes
void(object_type::* method_ptr)(arguments_type...)
object_type * object_ptr
Detailed Description
template<typename object_type, typename... arguments_type>
class xtd::fn::functor< object_type, arguments_type >
Definition at line 13 of file functor.hpp.
Constructor & Destructor Documentation
template<typename object_type , typename... arguments_type> xtd::fn::functor< object_type, arguments_type >::functor (object_type * object_ptr, void(object_type::*)(arguments_type...) method_ptr) inline explicit
Definition at line 20 of file functor.hpp.
References xtd::fn::functor< object_type, arguments_type >::method_ptr, and xtd::fn::functor< object_type, arguments_type >::object_ptr.
                {
                    if
                    (
                        object_ptr == nullptr
                            ||
                        method_ptr == nullptr
                    )
                    {
                        throw -1;
                    }
                    this->object_ptr = object_ptr;
                    this->method_ptr = method_ptr;
                }
template<typename object_type , typename... arguments_type> virtual xtd::fn::functor< object_type, arguments_type >::~functor (void) override virtual
Member Function Documentation
template<typename object_type , typename... arguments_type> virtual void xtd::fn::functor< object_type, arguments_type >::invoke (arguments_type... arguments) const inline override virtual
Implements xtd::fn::abstract_functor< arguments_type...>.
Definition at line 42 of file functor.hpp.
References xtd::fn::functor< object_type, arguments_type >::object_ptr.
Referenced by xtd::fn::functor< object_type, arguments_type >::operator()().
                {
                    ((this->object_ptr)->*(this->method_ptr))(arguments...);
                }
template<typename object_type , typename... arguments_type> virtual void xtd::fn::functor< object_type, arguments_type >::operator() (arguments_type... arguments) const inline override virtual
Implements xtd::fn::abstract_functor< arguments_type...>.
Definition at line 37 of file functor.hpp.
References xtd::fn::functor< object_type, arguments_type >::invoke().
                {
                    this->invoke(arguments...);
                }
Member Data Documentation
template<typename object_type , typename... arguments_type> void(object_type::* xtd::fn::functor< object_type, arguments_type >::method_ptr)(arguments_type...)
Definition at line 47 of file functor.hpp.
Referenced by xtd::fn::functor< object_type, arguments_type >::functor().
template<typename object_type , typename... arguments_type> object_type* xtd::fn::functor< object_type, arguments_type >::object_ptr
Definition at line 49 of file functor.hpp.
Referenced by xtd::fn::functor< object_type, arguments_type >::functor(), and xtd::fn::functor< object_type, arguments_type >::invoke().
The documentation for this class was generated from the following file:
sources/functional/functor/functor/sources/functor.hpp