XSTD: src/log/file_logger/tests/src/file_logger_tests.cpp File Reference
file_logger_tests.cpp File Reference
#include <gtest/gtest.h>
#include <log/file_logger.hpp>
Functions
TEST (file_logger, logs)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 36 of file file_logger_tests.cpp.
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST (file_logger , logs)
Definition at line 22 of file file_logger_tests.cpp.
References xstd::fs::get_file_contents(), xstd::abstract_logger::log(), and xstd::fs::truncate_file_contents().
{
    std::string log_file = "../tests/data/log";
    std::string log_data = "Hello world!";
    xstd::fs::truncate_file_contents(log_file);
    const xstd::abstract_logger& logger = xstd::file_logger(log_file,false,false);
    logger.log(log_data);
    ASSERT_EQ ( xstd::fs::get_file_contents(log_file) , log_data );
}