XTD: xstd::random Namespace Reference
xstd::random Namespace Reference
Functions
void randomize (void)
int get_int (int minimum, int maximum)
bool coin_flip (float win_rate_percent=50)
Function Documentation
bool xstd::random::coin_flip (float win_rate_percent = 50) inline
Definition at line 60 of file random.ipp.
References get_int().
Referenced by TEST().
        {
            if ( win_rate_percent > 100 )
            {
                win_rate_percent = 100;
            }
            if ( win_rate_percent < 0 )
            {
                win_rate_percent = 0;
            }
            int win_rate_inverted = 100 / win_rate_percent;
            return get_int(1,win_rate_inverted) == 1;
        }
int xstd::random::get_int (int minimum, int maximum) inline
Definition at line 33 of file random.ipp.
Referenced by coin_flip(), and TEST().
        {
            // Validate the range
            if ( minimum > maximum )
            {
                throw std::range_error("Invalid limits range");
            }
            // Minimum range
            else if ( minimum == maximum )
            {
                return minimum;
            }
            // Calculate the length of the range
            int range_length = maximum - minimum + 1;
            // Return a random number from the range
            return std::rand() % range_length + minimum;
        }
void xstd::random::randomize (void) inline
Definition at line 25 of file random.ipp.
Referenced by main().
        {
            // Randomize random number generator using vurent
            std::srand(std::time(nullptr));
        }