XTD: xtd::chrono Namespace Reference
xtd::chrono Namespace Reference
A namespace containing tools for time operations.
Functions
time_t time_point_to_time_t (const std::chrono::time_point< std::chrono::steady_clock > &time_point)
tm time_point_to_tm (const std::chrono::time_point< std::chrono::steady_clock > &time_point)
std::string time_point_to_formatted_string (const std::chrono::time_point< std::chrono::steady_clock > &time_point, const std::string &time_format)
std::string time_point_to_formatted_string_mt (const std::chrono::time_point< std::chrono::steady_clock > &time_point, const std::string &time_format)
Detailed Description
A namespace containing tools for time operations.
Function Documentation
std::string xtd::chrono::time_point_to_formatted_string (const std::chrono::time_point< std::chrono::steady_clock > & time_point, const std::string & time_format)
Definition at line 38 of file chrono_utils.cpp.
References time_point_to_time_t().
Referenced by xtd::log::abstract_logger::make_time_stamp(), TEST(), and time_point_to_formatted_string_mt().
std::string xtd::chrono::time_point_to_formatted_string_mt (const std::chrono::time_point< std::chrono::steady_clock > & time_point, const std::string & time_format)
Definition at line 76 of file chrono_utils.cpp.
References time_point_to_formatted_string().
time_t xtd::chrono::time_point_to_time_t (const std::chrono::time_point< std::chrono::steady_clock > & time_point)
Definition at line 9 of file chrono_utils.cpp.
Referenced by TEST(), time_point_to_formatted_string(), and time_point_to_tm().
tm xtd::chrono::time_point_to_tm (const std::chrono::time_point< std::chrono::steady_clock > & time_point)
Definition at line 28 of file chrono_utils.cpp.
References time_point_to_time_t().
Referenced by TEST().