XSTD: xstd::pp Namespace Reference
xstd::pp Namespace Reference
Classes
struct null_type
struct nth_type_helper
struct nth_type_helper< 0, first_parameter_type, other_parameters_types... >
struct nth_type_helper< parameter_id, first_parameter_type, other_parameters_types... >
struct nth_type
struct first_type
struct last_type
struct is_homogeneous
struct is_homogeneous< parameter_type >
struct is_homogeneous< first_parameter_type, other_parameters_types... >
struct is_heterogeneous
Functions
template<typename parameter_processor , typename... parameters_types>
void for_each (parameters_types...)
template<typename parameter_processor , typename first_parameter_type , typename... other_parameters_types>
void for_each (first_parameter_type first_parameter, other_parameters_types...other_parameters)
Function Documentation
template<typename parameter_processor , typename... parameters_types> void xstd::pp::for_each (parameters_types...)
Definition at line 29 of file parameter_pack_for_each.hpp.
Referenced by for_each(), and xstd::string_split().
        {
        }
template<typename parameter_processor , typename first_parameter_type , typename... other_parameters_types> void xstd::pp::for_each (first_parameter_type first_parameter, other_parameters_types... other_parameters)
Definition at line 35 of file parameter_pack_for_each.hpp.
References for_each().
        {
            parameter_processor::process(first_parameter);
            for_each<parameter_processor,other_parameters_types...>(other_parameters...);
        }