XTD: xtd::file Namespace Reference
xtd::file Namespace Reference
Functions
bool get_exists (const std::string &file_path)
off_t get_size (const std::string &file_path)
off_t get_size (int file_descriptor)
std::string get_contents (const std::string &file_path)
void set_contents (const std::string &file_path, const std::string &data)
void append_contents (const std::string &file_path, const std::string &data)
void prepend_contents (const std::string &file_path, const std::string &data)
void truncate_contents (const std::string &file_path)
void check_exists (const std::string &file_path)
Function Documentation
void xtd::file::append_contents (const std::string & file_path, const std::string & data)
Definition at line 116 of file file_utils.cpp.
References get_contents(), and set_contents().
Referenced by TEST().
        {
            set_contents(file_path,get_contents(file_path)+data);
        }
void xtd::file::check_exists (const std::string & file_path)
Definition at line 137 of file file_utils.cpp.
References get_exists().
Referenced by get_contents(), and set_contents().
        {
            if ( ! get_exists(file_path) )
            {
                throw std::runtime_error("File does not exist.");
            }
        }
std::string xtd::file::get_contents (const std::string & file_path)
Definition at line 66 of file file_utils.cpp.
References check_exists().
Referenced by append_contents(), prepend_contents(), and TEST().
        {
            check_exists(file_path);
            std::ifstream file_stream(file_path.data());
            if ( ! file_stream.is_open() )
            {
                throw std::runtime_error("Could no open file_path");
            }
            char file_character;
            std::string file_contents;
            while ( file_stream.good() && ! file_stream.eof() )
            {
                file_character = file_stream.get();
                if ( file_character != -1 )
                {
                    file_contents += file_character;
                }
            }
            file_stream.close();
            return file_contents;
        }
bool xtd::file::get_exists (const std::string & file_path)
Definition at line 9 of file file_utils.cpp.
Referenced by check_exists(), and TEST().
        {
            std::ifstream file_stream(file_path.data());
            if ( file_stream.is_open() )
            {
                file_stream.close();
                return true;
            }
            return false;
        }
off_t xtd::file::get_size (const std::string & file_path)
Definition at line 26 of file file_utils.cpp.
Referenced by TEST().
        {
            struct stat file_statistics;
            int get_file_statistics_result = stat(file_path.c_str(),&file_statistics);
            if ( get_file_statistics_result != 0 )
            {
                throw std::runtime_error("Could no retrieve file_path statistics");
            }
            off_t file_size = file_statistics.st_size;
            return file_size;
        }
off_t xtd::file::get_size (int file_descriptor)
Definition at line 46 of file file_utils.cpp.
        {
            struct stat file_statistics;
            int get_file_statistics_result = fstat(file_descriptor,&file_statistics);
            if ( get_file_statistics_result != 0 )
            {
                throw std::runtime_error("Could no retrieve file_path statistics");
            }
            off_t file_size = file_statistics.st_size;
            return file_size;
        }
void xtd::file::prepend_contents (const std::string & file_path, const std::string & data)
Definition at line 123 of file file_utils.cpp.
References get_contents(), and set_contents().
Referenced by TEST().
        {
            set_contents(file_path,data+get_contents(file_path));
        }
void xtd::file::set_contents (const std::string & file_path, const std::string & data)
Definition at line 103 of file file_utils.cpp.
References check_exists().
Referenced by append_contents(), prepend_contents(), TEST(), and truncate_contents().
        {
            check_exists(file_path);
            std::ofstream output_file_stream(file_path.data());
            output_file_stream.write(data.data(),data.size());
            output_file_stream.close();
        }
void xtd::file::truncate_contents (const std::string & file_path)
Definition at line 130 of file file_utils.cpp.
References set_contents().
Referenced by TEST().
        {
            set_contents(file_path,"");
        }