XTD: xtd::random Namespace Reference
xtd::random Namespace Reference
Functions
void randomize (void)
int get_int (const int minimum, const int maximum)
bool coin_flip (float win_rate_percent)
Function Documentation
bool xtd::random::coin_flip (float win_rate_percent)
Definition at line 44 of file random_utils.cpp.
References get_int().
Referenced by TEST().
        {
            if ( win_rate_percent >= 100 )
            {
                win_rate_percent = 100;
            }
            if ( win_rate_percent <= 0 )
            {
                win_rate_percent = 0;
            }
            int win_rate_inverted = 100 / win_rate_percent;
            return get_int(1,win_rate_inverted) == 1;
        }
int xtd::random::get_int (const int minimum, const int maximum)
Definition at line 17 of file random_utils.cpp.
Referenced by coin_flip(), and TEST().
        {
            //  Validate the range
            if ( minimum > maximum )
            {
                throw std::range_error("Invalid limits range");
            }
            //  Minimum range
            else if ( minimum == maximum )
            {
                return minimum;
            }
            //  Calculate the length of the range
            int range_length = maximum - minimum + 1;
            //  Return a random number from the range
            return std::rand() % range_length + minimum;
        }
void xtd::random::randomize (void)
Definition at line 9 of file random_utils.cpp.
Referenced by main().
        {
            //  Randomize random number generator using curent timestamp.
            std::srand(std::time(nullptr));
        }