XSTD: xstd::fs Namespace Reference
xstd::fs Namespace Reference
Functions
bool get_file_exists (const std::string &file_path)
off_t get_file_size (const std::string &file_path)
off_t get_file_size (int file_descriptor)
std::string get_file_contents (const std::string &file_path)
void set_file_contents (const std::string &file_path, const std::string &data)
void append_file_contents (const std::string &file_path, const std::string &data)
void prepend_file_contents (const std::string &file_path, const std::string &data)
void truncate_file_contents (const std::string &file_path)
void check_file_exists (const std::string &file_path)
Function Documentation
void xstd::fs::append_file_contents (const std::string & file_path, const std::string & data) inline
Definition at line 132 of file file_util.ipp.
References get_file_contents(), and set_file_contents().
Referenced by xstd::file_logger::log_data(), and TEST().
        {
            set_file_contents(file_path,get_file_contents(file_path)+data);
        }
void xstd::fs::check_file_exists (const std::string & file_path) inline
Definition at line 153 of file file_util.ipp.
References get_file_exists().
Referenced by get_file_contents(), and set_file_contents().
        {
            if ( ! get_file_exists(file_path) )
            {
                throw std::runtime_error("File does not exist.");
            }
        }
std::string xstd::fs::get_file_contents (const std::string & file_path) inline
Definition at line 82 of file file_util.ipp.
References check_file_exists().
Referenced by append_file_contents(), prepend_file_contents(), and TEST().
        {
            check_file_exists(file_path);
            std::ifstream file_stream(file_path.data());
            if ( ! file_stream.is_open() )
            {
                throw std::runtime_error("Could no open file_path");
            }
            char file_character;
            std::string file_contents;
            while ( file_stream.good() && ! file_stream.eof() )
            {
                file_character = file_stream.get();
                if ( file_character != -1 )
                {
                    file_contents += file_character;
                }
            }
            file_stream.close();
            return file_contents;
        }
bool xstd::fs::get_file_exists (const std::string & file_path) inline
Definition at line 25 of file file_util.ipp.
Referenced by check_file_exists(), and TEST().
        {
            std::ifstream file_stream(file_path.data());
            if ( file_stream.is_open() )
            {
                file_stream.close();
                return true;
            }
            return false;
        }
off_t xstd::fs::get_file_size (const std::string & file_path) inline
Definition at line 42 of file file_util.ipp.
Referenced by TEST().
        {
            struct stat file_statistics;
            int get_file_statistics_result = stat(file_path.c_str(),&file_statistics);
            if ( get_file_statistics_result != 0 )
            {
                throw std::runtime_error("Could no retrieve file_path statistics");
            }
            off_t file_size = file_statistics.st_size;
            return file_size;
        }
off_t xstd::fs::get_file_size (int file_descriptor) inline
Definition at line 62 of file file_util.ipp.
        {
            struct stat file_statistics;
            int get_file_statistics_result = fstat(file_descriptor,&file_statistics);
            if ( get_file_statistics_result != 0 )
            {
                throw std::runtime_error("Could no retrieve file_path statistics");
            }
            off_t file_size = file_statistics.st_size;
            return file_size;
        }
void xstd::fs::prepend_file_contents (const std::string & file_path, const std::string & data) inline
Definition at line 139 of file file_util.ipp.
References get_file_contents(), and set_file_contents().
Referenced by TEST().
        {
            set_file_contents(file_path,data+get_file_contents(file_path));
        }
void xstd::fs::set_file_contents (const std::string & file_path, const std::string & data) inline
Definition at line 119 of file file_util.ipp.
References check_file_exists().
Referenced by append_file_contents(), prepend_file_contents(), TEST(), and truncate_file_contents().
        {
            check_file_exists(file_path);
            std::ofstream output_file_stream(file_path.data());
            output_file_stream.write(data.data(),data.size());
            output_file_stream.close();
        }
void xstd::fs::truncate_file_contents (const std::string & file_path) inline
Definition at line 146 of file file_util.ipp.
References set_file_contents().
Referenced by TEST().
        {
            set_file_contents(file_path,"");
        }