XTD: xstd::chrono Namespace Reference
xstd::chrono Namespace Reference
Classes
class timer
class timer_base
class timer_manager
Functions
time_t time_point_to_time_t (const std::chrono::time_point< std::chrono::steady_clock > &time_point)
tm time_point_to_tm (const std::chrono::time_point< std::chrono::steady_clock > &time_point)
std::string time_point_to_formatted_string (const std::chrono::time_point< std::chrono::steady_clock > &time_point, const std::string &time_format="[%Y/%m/%d-%H:%M:%S]")
std::string time_point_to_formatted_string_mt (const std::chrono::time_point< std::chrono::steady_clock > &time_point, const std::string &time_format="[%Y/%m/%d-%H:%M:%S]")
Function Documentation
std::string xstd::chrono::time_point_to_formatted_string (const std::chrono::time_point< std::chrono::steady_clock > & time_point, const std::string & time_format = "[%Y/%m/%d-%H:%M:%S]") inline
Definition at line 54 of file chrono_util.ipp.
References time_point_to_time_t().
Referenced by xstd::abstract_logger::make_time_stamp(), TEST(), and time_point_to_formatted_string_mt().
std::string xstd::chrono::time_point_to_formatted_string_mt (const std::chrono::time_point< std::chrono::steady_clock > & time_point, const std::string & time_format = "[%Y/%m/%d-%H:%M:%S]") inline
Definition at line 92 of file chrono_util.ipp.
References time_point_to_formatted_string().
time_t xstd::chrono::time_point_to_time_t (const std::chrono::time_point< std::chrono::steady_clock > & time_point) inline
Definition at line 25 of file chrono_util.ipp.
Referenced by TEST(), time_point_to_formatted_string(), and time_point_to_tm().
tm xstd::chrono::time_point_to_tm (const std::chrono::time_point< std::chrono::steady_clock > & time_point) inline
Definition at line 44 of file chrono_util.ipp.
References time_point_to_time_t().
Referenced by TEST().