XTD: sources/random/tests/sources/random.cpp File Reference
random.cpp File Reference
#include <gtest/gtest.h>
#include <xtd/random.hpp>
#include <stdlib.h>
Functions
TEST (get_int_1_2, returns_1_or_2)
TEST (get_int_minus_5_minus_3, returns_minus_5_or_minus_4_or_minus_3)
TEST (get_int_2_1, throws_std_range_error)
TEST (coin_flip, returns_true_or_false)
TEST (coin_flip_10, returns_true_or_false)
TEST (coin_flip_10, returns_true_in_10_percents_of_cases)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 89 of file random.cpp.
References xtd::random::randomize().
{
    xtd::random::randomize();
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST (get_int_1_2 , returns_1_or_2)
Definition at line 5 of file random.cpp.
References xtd::random::get_int().
{
    int random_integer = xtd::random::get_int(1,2);
    ASSERT_TRUE
    (
        random_integer == 1
            ||
        random_integer == 2
    );
}
TEST (get_int_minus_5_minus_3 , returns_minus_5_or_minus_4_or_minus_3)
Definition at line 19 of file random.cpp.
References xtd::random::get_int().
{
    int random_integer = xtd::random::get_int(-5,-3);
    ASSERT_TRUE
    (
        random_integer == -5
            ||
        random_integer == -4
            ||
        random_integer == -3
    );
}
TEST (get_int_2_1 , throws_std_range_error)
Definition at line 35 of file random.cpp.
References xtd::random::get_int().
{
    ASSERT_THROW(xtd::random::get_int(2,1),std::range_error);
}
TEST (coin_flip , returns_true_or_false)
Definition at line 42 of file random.cpp.
References xtd::random::coin_flip().
{
    bool coin_flip = xtd::random::coin_flip();
    ASSERT_TRUE
    (
        coin_flip == true
            ||
        coin_flip == false
    );
}
TEST (coin_flip_10 , returns_true_or_false)
Definition at line 56 of file random.cpp.
References xtd::random::coin_flip().
{
    bool coin_flip = xtd::random::coin_flip(10);
    ASSERT_TRUE
    (
        coin_flip == true
            ||
        coin_flip == false
    );
}
TEST (coin_flip_10 , returns_true_in_10_percents_of_cases)
Definition at line 70 of file random.cpp.
References xtd::random::coin_flip().
{
    int wins = 0;
    int wins_expected = 1000;
    int threshold = 100;
    for ( int key = 0 ; key < 10000 ; key++ )
    {
        if ( xtd::random::coin_flip(10) == true )
        {
            wins++;
        }
    }
    ASSERT_TRUE ( abs(wins-wins_expected) < threshold );
}