XTD: sources/string/string_utils/tests/sources/to_int.hpp File Reference
to_int.hpp File Reference
Functions
TEST (to_int, effectively_converts_123_dec_000)
TEST (to_int, effectively_converts_123_dec_001)
TEST (to_int, effectively_converts_567_oct_000)
TEST (to_int, effectively_converts_567_oct_001)
TEST (to_int, effectively_converts_abc_hex_000)
TEST (to_int, effectively_converts_abc_hex_001)
TEST (to_int, effectively_converts_minus_abc_hex_000)
TEST (to_int, effectively_converts_minus_abc_hex_001)
TEST (to_int, effectively_converts_minus_111_bin)
TEST (to_int, effectively_converts_0)
TEST (to_int, effectively_converts_0abc)
TEST (to_int, effectively_converts_123_with_three_leading_spaces)
TEST (to_int, effectively_converts_a_floating_point_number)
TEST (to_int, fails_to_parse_a_string_containing_only_spaces)
TEST (to_int, fails_to_parse_abc)
TEST (to_int, fails_to_parse_abc123)
Function Documentation
TEST (to_int , effectively_converts_123_dec_000)
Definition at line 1 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "123";
    signed int result_number_correct = 123;
    signed int result_number_actual = xtd::str::to_int(source_string);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_123_dec_001)
Definition at line 9 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "123";
    signed int result_number_correct = 123;
    signed int result_number_actual = xtd::str::to_int(source_string,10);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_567_oct_000)
Definition at line 17 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "0567";
    signed int result_number_correct = 0567;
    signed int result_number_actual = xtd::str::to_int(source_string);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_567_oct_001)
Definition at line 25 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "0567";
    signed int result_number_correct = 0567;
    signed int result_number_actual = xtd::str::to_int(source_string,8);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_abc_hex_000)
Definition at line 33 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "0xABC";
    signed int result_number_correct = 0xABC;
    signed int result_number_actual = xtd::str::to_int(source_string);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_abc_hex_001)
Definition at line 41 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "0xABC";
    signed int result_number_correct = 0xABC;
    signed int result_number_actual = xtd::str::to_int(source_string,16);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_minus_abc_hex_000)
Definition at line 49 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "-0xABC";
    signed int result_number_correct = -0xABC;
    signed int result_number_actual = xtd::str::to_int(source_string);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_minus_abc_hex_001)
Definition at line 57 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "-0xABC";
    signed int result_number_correct = -0xABC;
    signed int result_number_actual = xtd::str::to_int(source_string,16);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_minus_111_bin)
Definition at line 65 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "-111";
    signed int result_number_correct = -7;
    signed int result_number_actual = xtd::str::to_int(source_string,2);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_0)
Definition at line 73 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "0";
    signed int result_number_correct = 0;
    signed int result_number_actual = xtd::str::to_int(source_string);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_0abc)
Definition at line 81 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "0ABC";
    signed int result_number_correct = 0;
    signed int result_number_actual = xtd::str::to_int(source_string);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_123_with_three_leading_spaces)
Definition at line 89 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "   123";
    signed int result_number_correct = 123;
    signed int result_number_actual = xtd::str::to_int(source_string);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , effectively_converts_a_floating_point_number)
Definition at line 97 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "5667857.999";
    signed int result_number_correct = 5667857;
    signed int result_number_actual = xtd::str::to_int(source_string);
    ASSERT_EQ ( result_number_correct , result_number_actual );
}
TEST (to_int , fails_to_parse_a_string_containing_only_spaces)
Definition at line 105 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "     ";
    ASSERT_THROW( xtd::str::to_int(source_string) , std::runtime_error );
}
TEST (to_int , fails_to_parse_abc)
Definition at line 111 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "ABC";
    ASSERT_THROW ( xtd::str::to_int(source_string) , std::runtime_error );
}
TEST (to_int , fails_to_parse_abc123)
Definition at line 117 of file to_int.hpp.
References xtd::str::to_int().
{
    std::string source_string = "ABC123";
    ASSERT_THROW ( xtd::str::to_int(source_string) , std::runtime_error );
}