XSTD: src/chrono/chrono_util/tests/src/chrono_util_tests.cpp File Reference
chrono_util_tests.cpp File Reference
#include <gtest/gtest.h>
#include <cstring>
#include <chrono/chrono_util.hpp>
Functions
TEST (one_second_time_point, converts_to_time_t_equal_to_1)
TEST (one_second_time_point, converts_to_string_1970_01_01_00_00_01)
TEST (one_minute_time_point, converts_to_time_t_equal_to_60)
TEST (one_minute_time_point, converts_to_equal_tm)
TEST (one_hour_time_point, converts_to_time_t_equal_to_3600)
TEST (one_hour_time_point, converts_to_sting_with_custom_format)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 86 of file chrono_util_tests.cpp.
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST (one_second_time_point , converts_to_time_t_equal_to_1)
Definition at line 23 of file chrono_util_tests.cpp.
References xstd::chrono::time_point_to_time_t().
{
    std::chrono::time_point<std::chrono::steady_clock> time_point(std::chrono::seconds(1));
    time_t time_point_in_time_t_format = xstd::chrono::time_point_to_time_t(time_point);
    ASSERT_EQ(time_point_in_time_t_format,1);
}
TEST (one_second_time_point , converts_to_string_1970_01_01_00_00_01)
Definition at line 33 of file chrono_util_tests.cpp.
References xstd::chrono::time_point_to_formatted_string().
{
    std::chrono::time_point<std::chrono::steady_clock> time_point(std::chrono::seconds(1));
    std::string time_point_string = xstd::chrono::time_point_to_formatted_string(time_point);
    ASSERT_EQ(time_point_string,"[1970/01/01-00:00:01]");
}
TEST (one_minute_time_point , converts_to_time_t_equal_to_60)
Definition at line 43 of file chrono_util_tests.cpp.
References xstd::chrono::time_point_to_time_t().
{
    std::chrono::time_point<std::chrono::steady_clock> time_point(std::chrono::minutes(1));
    time_t time_point_in_time_t_format = xstd::chrono::time_point_to_time_t(time_point);
    ASSERT_EQ(time_point_in_time_t_format,60);
}
TEST (one_minute_time_point , converts_to_equal_tm)
Definition at line 53 of file chrono_util_tests.cpp.
References xstd::chrono::time_point_to_tm().
{
    std::chrono::time_point<std::chrono::steady_clock> time_point(std::chrono::minutes(1));
    tm time_point_in_tm_format_actual = xstd::chrono::time_point_to_tm(time_point);
    time_t time_point_in_time_t_format = 60;
    tm time_point_in_tm_format_correct = *gmtime(&time_point_in_time_t_format);
    ASSERT_EQ(memcmp(&time_point_in_tm_format_actual,&time_point_in_tm_format_correct,sizeof(tm)),0);
}
TEST (one_hour_time_point , converts_to_time_t_equal_to_3600)
Definition at line 66 of file chrono_util_tests.cpp.
References xstd::chrono::time_point_to_time_t().
{
    std::chrono::time_point<std::chrono::steady_clock> time_point(std::chrono::hours(1));
    time_t time_point_in_time_t_format = xstd::chrono::time_point_to_time_t(time_point);
    ASSERT_EQ(time_point_in_time_t_format,3600);
}
TEST (one_hour_time_point , converts_to_sting_with_custom_format)
Definition at line 76 of file chrono_util_tests.cpp.
References xstd::chrono::time_point_to_formatted_string().
{
    std::chrono::time_point<std::chrono::steady_clock> time_point(std::chrono::seconds(42));
    std::string time_point_string = xstd::chrono::time_point_to_formatted_string(time_point,"%Y-%m-%d %H-%M-%S");
    ASSERT_EQ(time_point_string,"1970-01-01 00-00-42");
}