XSTD: xstd::point< type, dimension > Class Template Reference
xstd::point< type, dimension > Class Template Reference
#include <point.hpp>
Public Member Functions
point (void)
point (const coordinates_initializer_list &coordinates_object)
template<typename _type >
point (const point< _type, dimension > &point_object)
template<typename _type >
point & operator= (const point< _type, dimension > &point_object)
type & operator[] (const int coordinateId)
const type & operator[] (const int coordinateId) const
template<typename _type >
bool operator== (const point< _type, dimension > &point_object) const
template<typename _type >
bool operator!= (const point< _type, dimension > &point_object) const
template<typename _type >
point operator+ (const point< _type, dimension > &point_object) const
template<typename _type >
point operator- (const point< _type, dimension > &point_object) const
point operator* (const float multiplier) const
point operator/ (const float multiplier) const
int get_dimension (void) const
type get_coordinate_value (const int coordinateId) const
coordinates & get_coordinates_ref (void)
const coordinates & get_coordinates_ref (void) const
template<typename _type >
float get_distance_to (const point< _type, dimension > &point_object) const
template<typename _type >
void set_coordinates_values (const _type &coordinatesValue)
void set_coordinates_values (const coordinates_initializer_list &coordinates_object)
template<typename _type >
void set_coordinates_values (const std::array< _type, dimension > &coordinates_object)
void validate_dimension_match (const coordinates_initializer_list &coordinates_object) const
template<typename _type , int _dimension>
void validate_dimension_match (const point< _type, _dimension > &) const
void validate_coordinate_id (const int coordinateId) const
void validate_dimension (void) const
Protected Attributes
coordinates coordinates_object
Friends
std::ostream & operator<< (std::ostream &outputStream, const point &point_object)
Detailed Description
template<typename type, int dimension>
class xstd::point< type, dimension >
Definition at line 34 of file point.hpp.
Constructor & Destructor Documentation
template<typename type, int dimension> xstd::point< type, dimension >::point (void) inline
template<typename type, int dimension> xstd::point< type, dimension >::point (const coordinates_initializer_list & coordinates_object) inline
template<typename type, int dimension> template<typename _type > xstd::point< type, dimension >::point (const point< _type, dimension > & point_object) inline
Definition at line 52 of file point.hpp.
References xstd::point< type, dimension >::get_coordinates_ref(), and xstd::point< type, dimension >::set_coordinates_values().
            {
                this->set_coordinates_values(point_object.get_coordinates_ref());
            }
Member Function Documentation
template<typename type, int dimension> type xstd::point< type, dimension >::get_coordinate_value (const int coordinateId) const inline
template<typename type, int dimension> coordinates& xstd::point< type, dimension >::get_coordinates_ref (void) inline
Referenced by xstd::point< type, dimension >::operator=(), and xstd::point< type, dimension >::point().
template<typename type, int dimension> const coordinates& xstd::point< type, dimension >::get_coordinates_ref (void) const inline
template<typename type, int dimension> int xstd::point< type, dimension >::get_dimension (void) const inline
template<typename type, int dimension> template<typename _type > float xstd::point< type, dimension >::get_distance_to (const point< _type, dimension > & point_object) const inline
Definition at line 178 of file point.hpp.
References xstd::point< type, dimension >::coordinates_object.
            {
                float distanceSquared = 0;
                for ( int key = 0 ; key != dimension ; key++ )
                {
                    float coordinateA = this->coordinates_object[key];
                    float coordinateB = point_object.coordinates_object[key];
                    distanceSquared += ( coordinateB - coordinateA ) * ( coordinateB - coordinateA );
                }
                float distance = sqrt(distanceSquared);
                return distance;
            }
template<typename type, int dimension> template<typename _type > bool xstd::point< type, dimension >::operator!= (const point< _type, dimension > & point_object) const inline
Definition at line 133 of file point.hpp.
            {
                return ! ( *this == point_object );
            }
template<typename type, int dimension> point xstd::point< type, dimension >::operator* (const float multiplier) const inline
template<typename type, int dimension> template<typename _type > point xstd::point< type, dimension >::operator+ (const point< _type, dimension > & point_object) const inline
Definition at line 141 of file point.hpp.
            {
                point pointResult = *this;
                for ( int key = 0 ; key < dimension ; key++ )
                {
                    pointResult[key] += point_object[key];
                }
                return pointResult;
            }
template<typename type, int dimension> template<typename _type > point xstd::point< type, dimension >::operator- (const point< _type, dimension > & point_object) const inline
Definition at line 158 of file point.hpp.
            {
                return (*this)+(point_object*(-1));
            }
template<typename type, int dimension> point xstd::point< type, dimension >::operator/ (const float multiplier) const inline
template<typename type, int dimension> template<typename _type > point& xstd::point< type, dimension >::operator= (const point< _type, dimension > & point_object) inline
Definition at line 60 of file point.hpp.
References xstd::point< type, dimension >::get_coordinates_ref(), and xstd::point< type, dimension >::set_coordinates_values().
            {
                this->set_coordinates_values(point_object.get_coordinates_ref());
                return *this;
            }
template<typename type, int dimension> template<typename _type > bool xstd::point< type, dimension >::operator== (const point< _type, dimension > & point_object) const inline
Definition at line 113 of file point.hpp.
            {
                for ( int key = 0 ; key < dimension ; key++ )
                {
                    if ( this->coordinates_object[key] != point_object[key] )
                    {
                        return false;
                    }
                }
                return true;
            }
template<typename type, int dimension> type& xstd::point< type, dimension >::operator[] (const int coordinateId) inline
Definition at line 94 of file point.hpp.
References xstd::point< type, dimension >::validate_coordinate_id().
            {
                this->validate_coordinate_id(coordinateId);
                return this->coordinates_object[coordinateId];
            }
template<typename type, int dimension> const type& xstd::point< type, dimension >::operator[] (const int coordinateId) const inline
Definition at line 103 of file point.hpp.
References xstd::point< type, dimension >::validate_coordinate_id().
            {
                this->validate_coordinate_id(coordinateId);
                return this->coordinates_object[coordinateId];
            }
template<typename type, int dimension> template<typename _type > void xstd::point< type, dimension >::set_coordinates_values (const _type & coordinatesValue) inline
Definition at line 200 of file point.hpp.
Referenced by xstd::point< type, dimension >::operator=(), and xstd::point< type, dimension >::point().
            {
                /*
                    Set all coordinates_object values to `coordinatesValue`
                */
                this->coordinates_object.fill(coordinatesValue);
            }
template<typename type, int dimension> void xstd::point< type, dimension >::set_coordinates_values (const coordinates_initializer_list & coordinates_object) inline
Definition at line 213 of file point.hpp.
            {
                coordinates_initializer_list_itr coordinatesItr = coordinates_object.begin();
                int coordinateId = 0;
                for ( ; coordinatesItr != coordinates_object.end() ; coordinatesItr++ , coordinateId++ )
                {
                    this->coordinates_object[coordinateId] = *coordinatesItr;
                }
            }
template<typename type, int dimension> template<typename _type > void xstd::point< type, dimension >::set_coordinates_values (const std::array< _type, dimension > & coordinates_object) inline
Definition at line 229 of file point.hpp.
            {
                for ( int key = 0 ; key < dimension ; key++ )
                {
                    this->coordinates_object[key] = coordinates_object[key];
                }
            }
template<typename type, int dimension> void xstd::point< type, dimension >::validate_coordinate_id (const int coordinateId) const
Referenced by xstd::point< type, dimension >::operator[]().
template<typename type, int dimension> void xstd::point< type, dimension >::validate_dimension (void) const
template<typename type, int dimension> void xstd::point< type, dimension >::validate_dimension_match (const coordinates_initializer_list & coordinates_object) const inline
Definition at line 241 of file point.hpp.
            {
                if ( coordinates_object.size() != dimension )
                {
                    throw dimension_mismatch();
                }
            }
template<typename type, int dimension> template<typename _type , int _dimension> void xstd::point< type, dimension >::validate_dimension_match (const point< _type, _dimension > &) const inline
Definition at line 254 of file point.hpp.
            {
                if ( dimension != _dimension )
                {
                    throw dimension_mismatch();
                }
            }
Friends And Related Function Documentation
template<typename type, int dimension> std::ostream& operator<< (std::ostream & outputStream, const point< type, dimension > & point_object) friend
Definition at line 69 of file point.hpp.
            {
                outputStream << "point(";
                for ( int coordinateKey = 0 ; coordinateKey < dimension ; coordinateKey++ )
                {
                    outputStream << point_object.get_coordinate_value(coordinateKey);
                    if ( coordinateKey < dimension -1 )
                    {
                        outputStream << ",";
                    }
                }
                outputStream << ")";
                return outputStream;
            }
Member Data Documentation
template<typename type, int dimension> coordinates xstd::point< type, dimension >::coordinates_object protected
Definition at line 272 of file point.hpp.
Referenced by xstd::point< type, dimension >::get_distance_to().
The documentation for this class was generated from the following file:
/home/kolyunya/projects/xstd/src/cmath/point/src/point.hpp