XSTD: xstd::logger_client Class Reference
xstd::logger_client Class Reference
#include <logger_client.hpp>
Public Member Functions
logger_client (abstract_logger *logger_ptr=nullptr)
abstract_logger & get_logger_ref (void)
abstract_logger * get_logger_ptr (void)
void set_logger (abstract_logger *logger_ptr=nullptr)
void log (const std::string &data) const
Protected Attributes
abstract_logger * logger_ptr
Detailed Description
Definition at line 27 of file logger_client.hpp.
Constructor & Destructor Documentation
xstd::logger_client::logger_client (abstract_logger * logger_ptr = nullptr) inline explicit
Definition at line 22 of file logger_client.ipp.
References set_logger().
    {
        this->set_logger(logger_ptr);
    }
Member Function Documentation
abstract_logger * xstd::logger_client::get_logger_ptr (void) inline
Definition at line 36 of file logger_client.ipp.
References logger_ptr.
    {
        return this->logger_ptr;
    }
abstract_logger & xstd::logger_client::get_logger_ref (void) inline
Definition at line 29 of file logger_client.ipp.
References logger_ptr.
Referenced by TEST().
    {
        return * this->logger_ptr;
    }
void xstd::logger_client::log (const std::string & data) const inline
Definition at line 50 of file logger_client.ipp.
References xstd::abstract_logger::log(), and logger_ptr.
Referenced by TEST().
    {
        if ( this->logger_ptr )
        {
            this->logger_ptr->log(data);
        }
    }
void xstd::logger_client::set_logger (abstract_logger * logger_ptr = nullptr) inline
Definition at line 43 of file logger_client.ipp.
References logger_ptr.
Referenced by logger_client().
    {
        this->logger_ptr = logger_ptr;
    }
Member Data Documentation
abstract_logger* xstd::logger_client::logger_ptr protected
Definition at line 44 of file logger_client.hpp.
Referenced by get_logger_ptr(), get_logger_ref(), log(), and set_logger().
The documentation for this class was generated from the following files:
src/log/logger_client/src/logger_client.hpp
src/log/logger_client/src/logger_client.ipp