XSTD: /home/kolyunya/projects/xstd/src/fs/file_util/tests/src/file_util_tests.cpp File Reference
file_util_tests.cpp File Reference
#include <gtest/gtest.h>
#include <fs.hpp>
Functions
TEST (file_test_000_txt, exists)
TEST (file_test_42_dat, does_not_exist)
TEST (file_test_000_txt_contents, is_simple_test)
TEST (file_test_000_txt_size, is_11_bytes)
TEST (file_test_001_data_contents, is_simple_Cl_multiline_CL_test)
TEST (file_test_002_contents, is_read_correctly_by_std_fs_get_file_contents)
TEST (file_test_003_contents, is_empty)
TEST (file_test_004_contents, is_does_CL_it_CL_really_CL_work_CL)
TEST (get_file_contents, throws_runtime_error_while_trying_to_get_contents_of_a_file_which_does_not_exist)
TEST (std_fs_set_file_contents, sets_data_test_005_file_contents_to_hello_world_effectively)
TEST (std_fs_append_file_contents, appends_CL_appended_text_to_test_005_file)
TEST (std_fs_append_file_contents, prepends_CL_appended_text_to_test_005_file)
TEST (std_fs_truncate_file_contents, truncates_file_test_005_file_effectively)
int main (int argc, char **argv)
Variables
std::string path_to_unit_tests_data = "./../tests/data/"
Function Documentation
int main (int argc, char ** argv)
Definition at line 165 of file file_util_tests.cpp.
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST (file_test_000_txt , exists)
Definition at line 24 of file file_util_tests.cpp.
References xstd::fs::get_file_exists(), and path_to_unit_tests_data.
{
    ASSERT_TRUE ( xstd::fs::get_file_exists(path_to_unit_tests_data+"test_000.txt") );
}
TEST (file_test_42_dat , does_not_exist)
Definition at line 31 of file file_util_tests.cpp.
References xstd::fs::get_file_exists(), and path_to_unit_tests_data.
{
    ASSERT_FALSE ( xstd::fs::get_file_exists(path_to_unit_tests_data+"test_42.dat") );
}
TEST (file_test_000_txt_contents , is_simple_test)
Definition at line 38 of file file_util_tests.cpp.
References xstd::fs::get_file_contents(), and path_to_unit_tests_data.
{
    std::string file_path = path_to_unit_tests_data+"test_000.txt";
    std::string file_contents_expected = "simple test";
    std::string file_contents_actual = xstd::fs::get_file_contents(file_path);
    ASSERT_EQ ( file_contents_expected , file_contents_actual );
}
TEST (file_test_000_txt_size , is_11_bytes)
Definition at line 49 of file file_util_tests.cpp.
References xstd::fs::get_file_size(), and path_to_unit_tests_data.
{
    std::string file_path = path_to_unit_tests_data+"test_000.txt";
    off_t file_size_expected = 11;
    off_t file_size_actual = xstd::fs::get_file_size(file_path);
    ASSERT_EQ ( file_size_expected , file_size_actual );
}
TEST (file_test_001_data_contents , is_simple_Cl_multiline_CL_test)
Definition at line 60 of file file_util_tests.cpp.
References xstd::fs::get_file_contents(), and path_to_unit_tests_data.
{
    std::string file_path = path_to_unit_tests_data+"test_001.data";
    std::string file_contents_expected = "simple\nmultiline\ntest";
    std::string file_contents_actual = xstd::fs::get_file_contents(file_path);
    ASSERT_EQ ( file_contents_expected , file_contents_actual );
}
TEST (file_test_002_contents , is_read_correctly_by_std_fs_get_file_contents)
Definition at line 71 of file file_util_tests.cpp.
References xstd::fs::get_file_contents(), and path_to_unit_tests_data.
{
    std::string file_path = path_to_unit_tests_data+"test_002";
    std::string file_contents_expected = "multiline test with\nmany   spaces\nsome\ttablution\n\nempty lines\nand some special ,./-= characters\n\n";
    std::string file_contents_actual = xstd::fs::get_file_contents(file_path);
    ASSERT_EQ ( file_contents_expected , file_contents_actual );
}
TEST (file_test_003_contents , is_empty)
Definition at line 82 of file file_util_tests.cpp.
References xstd::fs::get_file_contents(), and path_to_unit_tests_data.
{
    std::string file_path = path_to_unit_tests_data+".test_003";
    std::string file_contents_expected = "";
    std::string file_contents_actual = xstd::fs::get_file_contents(file_path);
    ASSERT_EQ ( file_contents_expected , file_contents_actual );
}
TEST (file_test_004_contents , is_does_CL_it_CL_really_CL_work_CL)
Definition at line 93 of file file_util_tests.cpp.
References xstd::fs::get_file_contents(), and path_to_unit_tests_data.
{
    std::string file_path = path_to_unit_tests_data+"...test_004";
    std::string file_contents_expected = "does\nit\nreally\nwork\n?";
    std::string file_contents_actual = xstd::fs::get_file_contents(file_path);
    ASSERT_EQ ( file_contents_expected , file_contents_actual );
}
TEST (get_file_contents , throws_runtime_error_while_trying_to_get_contents_of_a_file_which_does_not_exist)
Definition at line 104 of file file_util_tests.cpp.
References xstd::fs::get_file_contents().
{
    ASSERT_THROW ( xstd::fs::get_file_contents("unexisting_file") , std::runtime_error );
}
TEST (std_fs_set_file_contents , sets_data_test_005_file_contents_to_hello_world_effectively)
Definition at line 111 of file file_util_tests.cpp.
References xstd::fs::get_file_contents(), path_to_unit_tests_data, and xstd::fs::set_file_contents().
{
    std::string file_path = path_to_unit_tests_data+"test_005";
    std::string file_contents_expected = "hello world";
    xstd::fs::set_file_contents(file_path,file_contents_expected);
    std::string file_contents_actual = xstd::fs::get_file_contents(file_path);
    ASSERT_EQ ( file_contents_expected , file_contents_actual );
}
TEST (std_fs_append_file_contents , appends_CL_appended_text_to_test_005_file)
Definition at line 123 of file file_util_tests.cpp.
References xstd::fs::append_file_contents(), xstd::fs::get_file_contents(), and path_to_unit_tests_data.
{
    std::string file_path = path_to_unit_tests_data+"test_005";
    std::string appended_text = "\nappended text";
    std::string file_contents_expected = "hello world" + appended_text;
    xstd::fs::append_file_contents(file_path,appended_text);
    std::string file_contents_actual = xstd::fs::get_file_contents(file_path);
    ASSERT_EQ ( file_contents_expected , file_contents_actual );
}
TEST (std_fs_append_file_contents , prepends_CL_appended_text_to_test_005_file)
Definition at line 137 of file file_util_tests.cpp.
References xstd::fs::get_file_contents(), path_to_unit_tests_data, and xstd::fs::prepend_file_contents().
{
    std::string file_path = path_to_unit_tests_data+"test_005";
    std::string prepended_text = "\nprepended text";
    std::string file_contents_expected = prepended_text + "hello world\nappended text";
    xstd::fs::prepend_file_contents(file_path,prepended_text);
    std::string file_contents_actual = xstd::fs::get_file_contents(file_path);
    ASSERT_EQ ( file_contents_expected , file_contents_actual );
}
TEST (std_fs_truncate_file_contents , truncates_file_test_005_file_effectively)
Definition at line 151 of file file_util_tests.cpp.
References xstd::fs::get_file_contents(), path_to_unit_tests_data, and xstd::fs::truncate_file_contents().
{
    std::string file_path = path_to_unit_tests_data+"test_005";
    xstd::fs::truncate_file_contents(file_path);
    std::string file_contents_expected = "";
    std::string file_contents_actual = xstd::fs::get_file_contents(file_path);
    ASSERT_EQ ( file_contents_expected , file_contents_actual );
}
Variable Documentation
std::string path_to_unit_tests_data = "./../tests/data/"
Definition at line 22 of file file_util_tests.cpp.
Referenced by TEST().