XSTD: src/log/logger_client/tests/src/logger_client_tests.cpp File Reference
logger_client_tests.cpp File Reference
#include <gtest/gtest.h>
#include <log/console_logger.hpp>
#include <log/logger_client.hpp>
Functions
TEST (logger_client, does_not_throw_while_construction)
TEST (logger_client, does_not_throw_while_logging_0)
TEST (logger_client, does_not_throw_while_logging_1)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 52 of file logger_client_tests.cpp.
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST (logger_client , does_not_throw_while_construction)
Definition at line 23 of file logger_client_tests.cpp.
{
    xstd::logger_client();
    ASSERT_TRUE(true);
}
TEST (logger_client , does_not_throw_while_logging_0)
Definition at line 31 of file logger_client_tests.cpp.
References xstd::logger_client::log().
{
    xstd::logger_client logger_client_obj;
    logger_client_obj.log("Hello world!");
    ASSERT_TRUE(true);
}
TEST (logger_client , does_not_throw_while_logging_1)
Definition at line 40 of file logger_client_tests.cpp.
References xstd::abstract_logger::add_new_line, xstd::abstract_logger::add_time_stamp, xstd::logger_client::get_logger_ref(), and xstd::logger_client::log().
{
    xstd::console_logger logger;
    xstd::logger_client logger_client(&logger);
    logger_client.get_logger_ref().add_new_line = false;
    logger_client.get_logger_ref().add_time_stamp = false;
    logger_client.log("");
    ASSERT_TRUE(true);
}