XTD: xstd::chrono::timer_manager Class Reference
xstd::chrono::timer_manager Class Reference
#include <timer_manager.hpp>
Public Member Functions
void add_timer (timer_base *const timer_ptr)
void remove_timer (timer_base *const timer_ptr)
Static Public Member Functions
static timer_manager & get_instance (void)
Private Member Functions
timer_manager (void)
virtual ~timer_manager (void) noexcept
bool has_timer (const timer_base *timer_ptr) const
void check_has_timer (const timer_base *timer_ptr) const
void check_has_no_timer (const timer_base *timer_ptr) const
void start_thread_if_needed (void)
void stop_thread_if_needed (void)
timers_vector_itr get_timer_itr (const timer_base *timer_ptr) const
timer_manager & operator= (timer_manager &)
Static Private Member Functions
static void thread_routine (const timer_manager *timer_manager_ptr)
Private Attributes
raii_thread_manual thread
std::recursive_mutex mutex
timers_vector timers
Detailed Description
Definition at line 33 of file timer_manager.hpp.
Constructor & Destructor Documentation
xstd::chrono::timer_manager::timer_manager (void) inline explicit private
Definition at line 63 of file timer_manager.hpp.
                                                :
                                                    thread(std::bind(timer_manager::thread_routine,this))
                {
                }
virtual xstd::chrono::timer_manager::~timer_manager (void) inline private virtual
Definition at line 70 of file timer_manager.hpp.
                {
                }
Member Function Documentation
void xstd::chrono::timer_manager::add_timer (timer_base *const timer_ptr) inline
Definition at line 45 of file timer_manager.hpp.
References check_has_no_timer(), mutex, start_thread_if_needed(), and timers.
Referenced by xstd::chrono::timer< clock >::start().
                {
                    std::lock_guard<std::recursive_mutex> lock_guard(this->mutex);
                    this->check_has_no_timer(timer_ptr);
                    this->timers.push_back(timer_ptr);
                    this->start_thread_if_needed();
                }
void xstd::chrono::timer_manager::check_has_no_timer (const timer_base * timer_ptr) const inline private
Definition at line 88 of file timer_manager.hpp.
References has_timer().
Referenced by add_timer().
                {
                    if ( this->has_timer(timer_ptr) == true )
                    {
                        throw std::runtime_error("Timer is already being managed");
                    }
                }
void xstd::chrono::timer_manager::check_has_timer (const timer_base * timer_ptr) const inline private
Definition at line 80 of file timer_manager.hpp.
References has_timer().
Referenced by remove_timer().
                {
                    if ( this->has_timer(timer_ptr) == false )
                    {
                        throw std::runtime_error("Timer is not being managed");
                    }
                }
static timer_manager& xstd::chrono::timer_manager::get_instance (void) inline static
Definition at line 37 of file timer_manager.hpp.
Referenced by xstd::chrono::timer< clock >::start(), and xstd::chrono::timer< clock >::stop().
                {
                    //  No mutex needed here because local statics are initialized in a thread-safe manner in C++11
                    //  and the "instance" is not modified after the instantiation
                    static timer_manager instance;
                    return instance;
                }
timers_vector_itr xstd::chrono::timer_manager::get_timer_itr (const timer_base * timer_ptr) const inline private
Definition at line 121 of file timer_manager.hpp.
References timers.
Referenced by has_timer(), and remove_timer().
                {
                    timers_vector_itr timers_vector_itr_obj = this->timers.begin();
                    for ( ; timers_vector_itr_obj != this->timers.end() ; timers_vector_itr_obj++ )
                    {
                        if ( *timers_vector_itr_obj == timer_ptr )
{
                            return timers_vector_itr_obj;
                        }
                    }
                    return this->timers.end();
                }
bool xstd::chrono::timer_manager::has_timer (const timer_base * timer_ptr) const inline private
Definition at line 75 of file timer_manager.hpp.
References get_timer_itr(), and timers.
Referenced by check_has_no_timer(), and check_has_timer().
                {
                    return this->get_timer_itr(timer_ptr) != this->timers.cend();
                }
timer_manager& xstd::chrono::timer_manager::operator= (timer_manager &) private
void xstd::chrono::timer_manager::remove_timer (timer_base *const timer_ptr) inline
Definition at line 53 of file timer_manager.hpp.
References check_has_timer(), get_timer_itr(), mutex, stop_thread_if_needed(), and timers.
Referenced by xstd::chrono::timer< clock >::stop().
                {
                    std::lock_guard<std::recursive_mutex> lock_guard(this->mutex);
                    this->check_has_timer(timer_ptr);
                    this->timers.erase(this->get_timer_itr(timer_ptr));
                    this->stop_thread_if_needed();
                }
void xstd::chrono::timer_manager::start_thread_if_needed (void) inline private
Definition at line 96 of file timer_manager.hpp.
References xstd::raii_thread_manual::start(), thread, and timers.
Referenced by add_timer().
                {
                    //  Starts the thread if there is exactly one active timer
                    //  If there are more than one timer the thread is already started
                    //  This function is called from "timer_manager::add_timer"
                    if ( this->timers.size() == 1 )
                    {
                        this->thread.start();
                    }
                }
void xstd::chrono::timer_manager::stop_thread_if_needed (void) inline private
Definition at line 109 of file timer_manager.hpp.
References xstd::raii_thread_manual::stop(), thread, and timers.
Referenced by remove_timer().
                {
                    //  Stops the thread if there are no active timers
                    //  This function is called from "timer_manager::add_timer"
                    if ( this->timers.empty() )
                    {
                        this->thread.stop();
                    }
                }
static void xstd::chrono::timer_manager::thread_routine (const timer_manager * timer_manager_ptr) inline static private
Definition at line 142 of file timer_manager.hpp.
References xstd::chrono::timer_base::tick(), and timers.
                {
                    for ( timer_base* timer_ptr : timer_manager_ptr->timers )
                    {
                        try
{
                            timer_ptr->tick();
                        }
                        catch ( ... )
{
                            continue;
                        }
                    }
                }
Member Data Documentation
std::recursive_mutex xstd::chrono::timer_manager::mutex private
Definition at line 170 of file timer_manager.hpp.
Referenced by add_timer(), and remove_timer().
raii_thread_manual xstd::chrono::timer_manager::thread private
Definition at line 168 of file timer_manager.hpp.
Referenced by start_thread_if_needed(), and stop_thread_if_needed().
timers_vector xstd::chrono::timer_manager::timers mutable private
Definition at line 172 of file timer_manager.hpp.
Referenced by add_timer(), get_timer_itr(), has_timer(), remove_timer(), start_thread_if_needed(), stop_thread_if_needed(), and thread_routine().
The documentation for this class was generated from the following file:
src/chrono/timer/timer_manager/src/timer_manager.hpp